---
title: "Animal annex"
output:
  pdf_document:
    latex_engine: xelatex
params:
    language: 'Swahili'
    relevant: FALSE
    include_variable_names: FALSE
    choice_names_too: FALSE
---


```{r setup, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = FALSE, 
               cache = FALSE,
               fig.width = 8.64,
               fig.height = 4.86,
               fig.path = 'figures/')
```

```{r}
library(bohemia)
```


2020-05-07. Version 1

(... = list of options continues)

```{r}
source('../../rpackage/bohemia/R/generate_data_dictionary.R')
library(readxl)
library(dplyr)
library(knitr)
library(stringr)
library(kableExtra)
lang <- params$language
rel <- params$relevant
var <- params$include_variable_names
cn <- params$choice_names_too
data_dict <- generate_data_dictionary(path = '../../forms/animalannex/animalannex.xlsx',
                                      language = lang, 
                                      include_variable_names = var, 
                                      include_relevant = rel, 
                                      shorten_many = 10, 
                                      choice_names_too = cn)
# Identify which are 
```

```{r}

# dt_lb <- data.frame(
# Item = c("Hello\nWorld", "This\nis a cat"),
# Value = c(10, 100)
# )
# dt_lb %>%
# mutate_all(linebreak) %>%
# kable("latex", booktabs = T, escape = F,
# col.names = linebreak(c("Item\n(Name)", "Value\n(Number)"), align = "c"))

# Get rid of repeat rows

# Define the right columns to look for
if(var){
  col_numbers <- 2:3
} else {
  col_numbers <-1:2
}
deletesa <-  rep(FALSE, nrow(data_dict))
for(i in 2:nrow(data_dict)){
  # message(i)
  samea <- as.character(unlist(data_dict[i,col_numbers[1]])) == as.character(unlist(data_dict[i-1,col_numbers[1]]))
      sameb <- as.character(unlist(data_dict[i,col_numbers[2]])) == as.character(unlist(data_dict[i-1,col_numbers[2]]))

  if(!is.na(samea) & !is.na(sameb)){
    if(samea & sameb){
    deletesa[i] <- TRUE
  }
  }
}

data_dict[deletesa,1] <- ' '
data_dict[deletesa,2] <- ' '

# Deal with line breaks
line_breaker <- function(x,n = 10){
  gsub(paste0('(.{1,',n,'})(\\s|$)'), '\\1\n', x)
}
# nn <- 50
# long_vars <- which(names(dd) %in% c('Questão', 'Swali', 'Question', 'Relevance'))
# for(i in 1:nrow(data_dict)){
#   for(j in long_vars){
#     # message(i)
#     val <- as.character(unlist(data_dict[i,j]))
#     if(!is.na(val)){
#       if(nchar(val) > nn){
#       data_dict[i,j] <- line_breaker(val, nn)
#     }
#     }
#   }
# }

# removes <- which(grepl('_', data_dict$Swali, fixed = T))
# dd <- data_dict[!1:nrow(data_dict) %in% removes,]

dd <- data_dict
trim.trailing <- function (x) sub("\\n+$", "", x)

clean_up <- function(zz){
  trim.trailing(
    gsub(']', '', 
         gsub('[', '',
    gsub('_', ' ', 
         gsub('$', '', as.character(unlist(zz)), fixed = TRUE), fixed = TRUE),
    fixed = TRUE), fixed = TRUE))
}

question_var <- which(names(dd) %in% c('Questão', 'Swali', 'Question'))[1]
dd[,question_var] <- clean_up(dd[,question_var])
if(rel){
  rel_var <- which(names(dd) %in% c('Relevance'))[1]
  dd[,rel_var] <- clean_up(dd[,rel_var])
}

# Define hlines after
hlas <- which(as.character(unlist(dd[,question_var])) != ' ') -1

out <- dd %>%
  mutate_all(linebreak) %>%
  kable("latex", escape=F, longtable = TRUE,
        booktabs = T,
        linesep = "") %>%
  kable_styling(font_size = 9,
                full_width = T,
                latex_options = c('repeat_header')) 

if(!rel){
  out <- out %>%
   column_spec(question_var, width = "7cm")
}

out

# for(i in hlas){
#   out <- out %>%
#     row_spec(i, hline_after = TRUE)
# }

#%>%
#   kable_styling(full_width = T,
#                 font_size = 9,
#                 latex_options = 
#                   c("striped",
#                     "repeat_header")) %>%
  #%>%
  # kable_styling()
  # collapse_rows(2)
             # booktabs = T,
             # escape = FALSE, col.names = linebreak(names(data_dict)), align = "c")


  # kable_styling(latex_options = c("repeat_header", full_width = T)) %>%
  # collapse_rows(columns = 1:2, latex_hline = "major", valign = "middle")
# kable_styling(latex_options = "striped")
# data_dict
```
