---
title: 'Location of Mopeia hamlets'
output: html_document
---

```{r setup, include=FALSE, echo = FALSE}
# Basic knitr options
library(knitr)
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = FALSE,
               fig.width = 8.64,
               fig.height = 4.86,
               fig.path = 'figures/')
```


```{r}
# Libraries
library(tidyverse)
library(bohemia)
```

The below map shows the (estimated) borders of Mopeia hamlets based on the COST study. This map was produced using [this code](https://github.com/databrew/bohemia/blob/master/rpackage/bohemia/data-raw/create_data_files.R#L14), run on the raw census data from the COST trial. It uses an automated error detection algorithm to identify suspect incorrect households and remove them, and then employs tesselation to estimate borders.

```{r}
cols <- rainbow(nrow(mopeia_hamlets))
cols <- sample(cols, length(cols))
cols <- sample(cols, length(cols))

library(leaflet)
leaflet() %>%
  addTiles() %>%
  addPolygons(data = mopeia_hamlets,
              color = cols,
              popup = paste0(mopeia_hamlets$id,
                             ', Village: ',
                             mopeia_hamlets$village,
                             ', Locality:',
                             mopeia_hamlets$locality),
              weight = 1)

```