---
params:
  data: !r data.frame(a = 1, b = 2, x = 4, xx=5,xy=6,xyz=8, yy=9,yz=11,zz=12) 
output:
  pdf_document:
    keep_tex: yes
    includes:
      in_header: list_preamble.sty
tables: yes
---

```{r setup, include=FALSE}
# output: 
#   pdf_document:
#     latex_engine: xelatex
#      pandoc_args: [
#      "-V", "classoption=twocolumn"
#    ]
#     template: pdf/layout.tex
#     includes:
#       in_header: pdf/preamble.sty
library(knitr)# Basic knitr options
opts_chunk$set(comment = NA, 
               echo = FALSE, 
               warning = FALSE, 
               message = FALSE, 
               error = TRUE, 
               cache = F,
               fig.height = 6)
# knit_engines$set(asis = function(options) {
#   if (options$echo && options$eval) knit_child(text = options$code)
# })
```


```{r}
library(dplyr)
options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)
# Specify paramaters
for (i in 1:length(params)){
  assign(names(params)[i],
         params[[i]],
         env = .GlobalEnv)
}
dfx <- params$data
```

Consent verification list

\pagenumbering{gobble}
\begin{landscape}



```{r}
# load('/tmp/data.RData')
# data <- pdx
# save(dfx, file = '/tmp/dfx.RData')
kable(dfx, 'latex',  
      # booktabs = F,
      longtable = T)  %>%   
  kable_styling(latex_options = c('striped',
                                'repeat_header')) %>%
    kable_styling(font_size = 6)  %>%
  column_spec(1:2, width = '1.6cm') %>%
  column_spec(3:4, width = '1.7cm') %>%
  column_spec(5, width = '1cm') %>%
  column_spec(6:ncol(dfx), width = '2.5cm')
```

\end{landscape}


End.

