#' Format va ODK data for the bohemia database
#' 
#' Take the va data (as generated by "odk_get_data") and format it so it's ready for popping into the va table of the bohemia database
#' @param data The list of dataframes (non_repeats and repeats) generated by odk_get_data for va
#' @param keyfile The public key file to be used for encryption
#' @return A list of dataframes formatted and named in accordance with the bohemia database
#' @import dplyr
#' @export

format_va <- function(data, keyfile){
  
  ## MAIN PART OF va
  df <- data$non_repeats
  df <- df %>% dplyr::rename(instance_id = instanceID)
  names(df) <- tolower(names(df))
  # Remove all the notes
  df <- df[,!grepl('note_', names(df))]
  df$hamlet_code <- NULL
  df$hamlet_code_from_death_id <- NULL
  df$hh_id_from_death_id <- NULL
  
  # Make all names lowercase
  names(df) <- tolower(names(df))
  
  # Hide names
  make_initials <- function(a){
    unlist(lapply(lapply(strsplit(as.character(a), ' '), function(x){substr(as.character(x), 1, 1)}), function(y){toupper(paste0(y, collapse = ''))}))
  }
  if('id10007' %in% names(df)){
    df$id10007_initials <- make_initials(df$id10007)
    df$id10007 <- encrypt_private_data(data = df$id10007, keyfile = keyfile)
  }
  if('id10017' %in% names(df)){
    df$id10017_initials <- make_initials(df$id10017)
    df$id10017 <- encrypt_private_data(data = df$id10017, keyfile = keyfile)
  }
  if('id10018' %in% names(df)){
    df$id10018_initials <- make_initials(df$id10018)
    df$id10018 <- encrypt_private_data(data = df$id10018, keyfile = keyfile)
  }
  if('id10061' %in% names(df)){
    df$id10061_initials <- make_initials(df$id10061)
    df$id10061 <- encrypt_private_data(data = df$id10061, keyfile = keyfile)
  }
  if('id10062' %in% names(df)){
    df$id10062_initials <- make_initials(df$id10062_initials)
    df$id10062 <- encrypt_private_data(data = df$id10062, keyfile = keyfile)
  }
  df$hamlet_code <- df$hamlet_code_from_death_id <- df$hh_id_from_death_id <- df$the_district <- df$the_ward <- df$the_region <- df$the_country <- df$the_village <- df$the_hamlet <- NULL
  if('id10054d_other' %in% names(df)){
    df$id10054d <- ifelse(!is.na(df$id10054d_other),
                          df$id10054d_other,
                          df$id10054d)
    df$id10054d_other <- NULL
  }
  if('id10054r_other' %in% names(df)){
    df$id10054r <- ifelse(!is.na(df$id10054r_other),
                          df$id10054r_other,
                          df$id10054r)
    df$id10054r_other <- NULL
  }
  if('id10057d_other' %in% names(df)){
    df$id10057d <- ifelse(!is.na(df$id10057d_other),
                          df$id10057d_other,
                          df$id10057d)
    df$id10057d_other <- NULL
  }
  if('id10057r_other' %in% names(df)){
    df$id10057r <- ifelse(!is.na(df$id10057r_other),
                          df$id10057r_other,
                          df$id10057r)
    df$id10057r_other <- NULL
  }
  if('id10058c_other' %in% names(df)){
    df$id10058c <- ifelse(!is.na(df$id10058c_other),
                          df$id10058c_other,
                          df$id10058c)
    df$id10058c_other <- NULL
  }
  if('id10434_other' %in% names(df)){
    df$id10434 <- ifelse(!is.na(df$id10434_other),
                          df$id10434_other,
                          df$id10434)
    df$id10434_other <- NULL
  }
  df$the_district <- df$the_hamlet <- df$the_country <- df$the_ward <- df$the_village <- df$the_region <-  NULL
  
  # NO REPEATS IN va
  # Return the formatted data
  out <- list(df)
  names(out) <- c('va')
  # Clean up uuid column
  for(i in 1:length(out)){
    if('instance_id' %in% names(out[[i]])){
      out[[i]]$instance_id <- gsub('uuid:', '', out[[i]]$instance_id)
    }
    
  }
  return(out)
}
