#' Format refusals ODK data for the bohemia database
#' 
#' Take the refusals data (as generated by "odk_get_data") and format it so it's ready for popping into the refusals table of the bohemia database
#' @param data The list of dataframes (non_repeats and repeats) generated by odk_get_data for refusals
#' @return A list of dataframes formatted and named in accordance with the bohemia database
#' @import dplyr
#' @export

format_refusals <- function(data){
  
  ## MAIN PART OF refusals
  df <- data$non_repeats
  df <- df %>% dplyr::rename(instance_id = instanceID)
  names(df) <- tolower(names(df))
  # Remove all the notes
  df <- df[,!grepl('note_', names(df))]

  # Clean up some variables
  df <- df %>%
    # Hamlet and village clean-up
    mutate(hamlet = ifelse(!is.na(hh_hamlet_other),
                           hh_hamlet_other,
                           hh_hamlet)) %>%
    mutate(village = ifelse(!is.na(hh_village_other),
                            hh_village_other,
                            hh_village)) %>%
    mutate(hamlet_code = hh_hamlet_code) %>%
    mutate(country = hh_country,
           district = hh_district,
           region = hh_region,
           ward = hh_ward) %>%
    dplyr::select(-hh_hamlet_code_list,
                  -hh_hamlet_code_not_list,
                  -hh_hamlet_other,
                  -hh_hamlet,
                  -hh_village,
                  -hh_village_other,
                  -hh_other_location,
                  -hh_hamlet_code,
                  -hh_country,
                  -hh_region,
                  -hh_ward,
                  -hh_district) %>%
    # reason cleanup
    mutate(reason_no_participate = ifelse(!is.na(reason_no_participate_other),
                                          reason_no_participate_other,
                                         reason_no_participate)) %>%
    dplyr::select(-reason_no_participate_other) 
  
  # NO REPEATS IN refusalS
  # Return the formatted data
  out <- list(df)
  names(out) <- c('refusals')
  # Clean up uuid column
  for(i in 1:length(out)){
    if('instance_id' %in% names(out[[i]])){
      out[[i]]$instance_id <- gsub('uuid:', '', out[[i]]$instance_id)
    }
    
  }
  return(out)
}
