#' Format minicensus ODK data for the bohemia database
#' 
#' Take the minicensus data (as generated by "odk_get_data") and format it so it's ready for popping into the minicensus database
#' @param data The list of dataframes (non_repeats and repeats) generated by odk_get_data
#' @return A list of dataframes formatted and named in accordance with the bohemia database
#' @import dplyr
#' @export

format_minicensus <- function(data){
  
  ## MAIN PART OF MINICENSUS
  df <- data$non_repeats
  df <- df %>% dplyr::rename(instance_id = instanceID)
  # Extract the people columns
  people_columns <- c(paste0('first_name', 1:30),
                      paste0('last_name', 1:30),
                      paste0('pid', 1:30),
                      paste0('name_label', 1:30))
  # Divide between the people part and non people part
  people_part <- df[,people_columns] %>% mutate(instance_id = df$instance_id)
  df <- df[,!names(df) %in% people_columns]
  # Remove all the notes
  df <- df[,!grepl('note_', names(df))]
  df <- df[,!grepl('_warning', names(df))]
  # Remove a few extra columns
  df$non_residents_filled_out <- NULL
  df$residents_filled_out <- NULL

  # Clean up the people part
  people_list <- list()
  counter <- 0
  for(i in 1:nrow(people_part)){
    for(j in 1:30){
      counter <- counter + 1
      these_columns <- c(paste0('first_name', j),
                         paste0('last_name', j),
                         paste0('pid', j),
                         paste0('name_label', j))
      these_data <- people_part[i,these_columns]
      names(these_data) <- c('first_name', 'last_name', 'pid', 'name_label')
      these_data$num <- j
      these_data$instance_id <- people_part$instance_id[i]
      people_list[[counter]] <- these_data
    }
  }
  people_part <- bind_rows(people_list)
  people_part <- people_part %>% dplyr::filter(!is.na(pid))
  people_part <- people_part
  people_part$invisible_non_resident_count <- NULL
  people_part$invisible_resident_count <- NULL
  
  # Remove names
  people_part$name_label <- NULL
  people_part$first_name <- substr(people_part$first_name, 1, 1)
  people_part$last_name <- substr(people_part$last_name, 1, 1)
  
  # Clean up some variables
  if('hh_main_wall_material_free' %in% names(df)){
    df$hh_main_wall_material_other <- df$hh_main_wall_material_free
    df$hh_main_wall_material_free <- NULL
  }
  df <- df %>%
    # Hamlet and village clean-up
    mutate(hh_hamlet = ifelse(!is.na(hh_hamlet_other),
                              hh_hamlet_other,
                              hh_hamlet)) %>%
    mutate(hh_village = ifelse(!is.na(hh_village_other),
                               hh_village_other,
                               hh_village)) %>%
    dplyr::select(-hh_hamlet_code_list,
                  -hh_hamlet_code_not_list,
                  -hh_hamlet_other,
                  -hh_village_other,
                  -hh_other_location) %>%
    # Household ID clean up
    dplyr::select(-hh_id_manual) %>% # we can remove because hh_id just copies it
    # Main building type clean up
    mutate(hh_main_building_type = ifelse(!is.na(hh_main_building_type_other),
                                          hh_main_building_type_other,
                                          hh_main_building_type)) %>%
    dplyr::select(-hh_main_building_type_other) %>%
    # lighting clean up
    mutate(hh_main_energy_source_for_lighting = ifelse(!is.na(hh_main_energy_source_for_lighting_other),
                                                       hh_main_energy_source_for_lighting_other,
                                                       hh_main_energy_source_for_lighting)) %>%
    # The below are select multiple, so it's theoretically possible to combine the other option
    mutate(hh_main_wall_material = paste0(ifelse(!is.na(hh_main_wall_material), hh_main_wall_material, ''),
                                          ' ',
                                          ifelse(!is.na(hh_main_wall_material_other), hh_main_wall_material_other, ''))) %>%
    mutate(hh_health_permission = paste0(ifelse(!is.na(hh_health_permission), hh_health_permission, ''),
                                          ' ',
                                          ifelse(!is.na(hh_health_permission_other), hh_health_permission_other, ''))) %>%
    dplyr::select(-hh_main_energy_source_for_lighting_other,
                  -hh_main_wall_material_other,
                  -instanceName,
                  -hh_health_permission_other) %>%
    mutate(hh_contact_info_number_alternate = as.character(hh_contact_info_number_alternate),
           hh_contact_info_number = as.character(hh_contact_info_number))
  
  # REPEATS
  # death
  repeat_death_info <- data$repeats$repeat_death_info 
  repeat_death_info <- repeat_death_info %>% filter(!is.na(repeat_death_info_count))
  if(!is.null(repeat_death_info)){
    if(nrow(repeat_death_info) > 0){
      repeat_death_info <- repeat_death_info %>%
        dplyr::rename(instance_id = instanceID)
      repeat_death_info$repeat_name <- NULL
      repeat_death_info$repeated_id <- NULL
      repeat_death_info$death_adjustment <- NULL
      repeat_death_info$death_name <- substr(repeat_death_info$death_name, 1, 1)
      repeat_death_info$death_surname <- substr(repeat_death_info$death_surname, 1, 1)
      repeat_death_info <- repeat_death_info[,!grepl('note_|_warning', names(repeat_death_info))]
    } else {
      repeat_death_info <- NULL
    }
  }
    
  
  # hh_sub
  repeat_hh_sub <- data$repeats$repeat_hh_sub
  if(!is.null(repeat_hh_sub)){
    repeat_hh_sub <- repeat_hh_sub %>%
      dplyr::rename(instance_id = instanceID) %>% 
      dplyr::select(-repeat_name, 
                    -repeated_id,
                    -note_hh_head_is_sub) %>%
      mutate(hh_sub_relationship = ifelse(!is.na(hh_sub_relationship_other),
                                          hh_sub_relationship_other,
                                          hh_sub_relationship)) %>%
      dplyr::select(-hh_sub_relationship_other)
    repeat_hh_sub <- repeat_hh_sub[,!grepl('note_|_warning', names(repeat_hh_sub))]
    repeat_hh_sub$repeat_hh_sub_count <- NULL
  }
    
  
  # household members (joining to people part) 
  repeat_household_members_enumeration <- data$repeats$repeat_household_members_enumeration 
  if(!is.null(repeat_household_members_enumeration)){
    repeat_household_members_enumeration <- repeat_household_members_enumeration %>%
      dplyr::rename(instance_id = instanceID) %>% dplyr::select(-repeat_name, -repeated_id, -hh_member_number_size) %>% filter(!is.na(permid))
    repeat_household_members_enumeration <- repeat_household_members_enumeration[,!grepl('note_|_warning', names(repeat_household_members_enumeration))]
    repeat_household_members_enumeration$first_name <- repeat_household_members_enumeration$last_name <- NULL
    people <- people_part %>% left_join(repeat_household_members_enumeration %>%
                                          mutate(pid = permid))
    people$invisible_non_resident_count <- NULL
    people$invisible_resident_count <- NULL
  }
    

  # mosquito nets
  repeat_mosquito_net <- data$repeats$repeat_mosquito_net 
  if(!is.null(repeat_mosquito_net)){
    repeat_mosquito_net <- repeat_mosquito_net %>%
      dplyr::rename(instance_id = instanceID,
                    num = repeat_mosquito_net_count) %>% 
      dplyr::select(-repeat_name, -repeated_id) %>%
      filter(!is.na(num))
    repeat_mosquito_net <- repeat_mosquito_net[,!grepl('note_|_warning', names(repeat_mosquito_net))]
  }  
  
  
  # water 
  repeat_water <- data$repeats$repeat_water
  if(!is.null(repeat_water)){
    repeat_water <- repeat_water %>%
      dplyr::rename(instance_id = instanceID,
                    num = repeat_water_count) %>% 
      dplyr::select(-repeat_name, -repeated_id) %>%
      dplyr::filter(!is.na(num))
    repeat_water <- repeat_water[,!grepl('note_|_warning', names(repeat_water))]
  }  
  
  
  # Return the formatted data
  out <- list(df, people,
              repeat_death_info, repeat_hh_sub, repeat_mosquito_net,
              repeat_water)
  names(out) <- c('main', 'people', 'repeat_death_info', 'repeat_hh_sub', 'repeat_mosquito_net',
                  'repeat_water')
  names(out) <- paste0('minicensus_', names(out))
  # Clean up uuid column
  for(i in 1:length(out)){
    if(!is.null(out[[i]])){
      if('instance_id' %in% names(out[[i]])){
        out[[i]]$instance_id <- gsub('uuid:', '', out[[i]]$instance_id)
      }
    }
  }
  return(out)
}