#' Format va ODK data for the bohemia database
#' 
#' Take the va data (as generated by "odk_get_data") and format it so it's ready for popping into the va table of the bohemia database
#' @param data The list of dataframes (non_repeats and repeats) generated by odk_get_data for va
#' @return A list of dataframes formatted and named in accordance with the bohemia database
#' @import dplyr
#' @export

format_va <- function(data){
  
  ## MAIN PART OF va
  df <- data$non_repeats
  df <- df %>% dplyr::rename(instance_id = instanceID)
  names(df) <- tolower(names(df))
  # Remove all the notes
  df <- df[,!grepl('note_', names(df))]
  
  # Make all names lowercase
  names(df) <- tolower(names(df))

  
  # NO REPEATS IN va
  # Return the formatted data
  out <- list(df)
  names(out) <- c('va')
  # Clean up uuid column
  for(i in 1:length(out)){
    if('instance_id' %in% names(out[[i]])){
      out[[i]]$instance_id <- gsub('uuid:', '', out[[i]]$instance_id)
    }
    
  }
  return(out)
}
