#' ODK make wide
#' 
#' Take a list of long datasets (as generated by \code{odk_parse_submission}) and convert to "wide" format
#' @param long_list A list generated by \code{odk_parse_submission}
#' @import tidyr
#' @return A list of wide dataframes of identical length to the input
#' @export

odk_make_wide <- function(long_list){
  
  # Check to make sure thae contents are correct
  ok <- length(long_list) == 2
  if(!ok){
    stop('The input list should be of length 2')
  }
  ok <- all(names(long_list) %in% c('repeats', 'non_repeats'))
  if(!ok){
    stop('The names of the input list must be "repeats" and "non_repeats" only')
  }
  
  # All ok, widen repeats
  repeats <- long_list$repeats
  repeats_wide <- tidyr::spread(data = repeats,
                                key = key,
                                value = value,
                                convert = TRUE)
  
  # All ok, widen non repeats
  non_repeats <- long_list$non_repeats
  non_repeats_wide <- tidyr::spread(data = non_repeats,
                                key = key,
                                value = value,
                                convert = TRUE)
  
  # Pop back in the list and return
  out <- list(repeats = repeats_wide,
              non_repeats = non_repeats_wide)
  return(out)
}

