#' Update refusals data in the bohemia database
#' 
#' Take the formatted refusals data (as generated by "format_refusals") and update the data in the database
#' @param formatted_data A list of dataframes (just one actually) as generated by format_refusals
#' @param con The database connection
#' @param host The endpoint
#' @param user The database user
#' @param pass The database password
#' @param port the database bort
#' @param dbname The database name
#' @return Data will be updated in the database
#' @import dplyr
#' @import RPostgres
#' @export

update_refusals <- function(formatted_data,
                              con = NULL,
                              host = NULL,
                              user = NULL,
                              pass = NULL,
                              port = 5432,
                              dbname = 'bohemia'){
  
  if(is.null(con)){
    open_connection <- FALSE
    if( is.null(host) | 
        is.null(user) | 
        is.null(pass)){
      stop(paste('You must either supply a conneection (con) or host, user, pass, port and dbname are required in order to establish a connection.'))
    }
  } else {
    open_connection <- TRUE
  }
  # If no open connection establish one
  if(!open_connection){
    # Connect
    drv <- RPostgres::Postgres()
    con <- dbConnect(drv, 
                     dbname=dbname, 
                     host=host, 
                     port=port,
                     user=user, 
                     password=pass)
  }
  
  # UPDATE
  for(i in 1:length(formatted_data)){
    message(i)
    this_table <- formatted_data[[i]]
    this_name <- names(formatted_data)[i]
    dbWriteTable(con, this_name, value = this_table, append=TRUE, row.names=FALSE)
    
  }
  
  # Disconnect (only if not supplied an open connection)
  if(!open_connection){
    dbDisconnect(con)
  }
}
  