---
title: "GPS tracking"
author: "Databrew"
output: html_document
---

```{r}
library(bohemia)
library(tidyverse)
# read in credenstials 
creds <- yaml::yaml.load_file('../../credentials/credentials.yaml')

suppressMessages({
  library(RPostgres)
  library(bohemia)
  library(leafgl)
  library(sf)
  library(yaml)
  library(leaflet)
  library(readr)
}
)
psql_end_point = creds$endpoint
psql_user = creds$psql_master_username
psql_pass = creds$psql_master_password
drv <- RPostgres::Postgres()
con <- dbConnect(drv, dbname='bohemia', host=psql_end_point, 
                 port=5432,
                 user=psql_user, password=psql_pass)
traccar <- dbReadTable(conn = con, name = 'traccar')
dbDisconnect(con)
```

```{r}
# Define a default fieldworkers data
if(!'fids.csv' %in% dir('/tmp')){
  fids_url <- 'https://docs.google.com/spreadsheets/d/1o1DGtCUrlBZcu-iLW-reWuB3PC8poEFGYxHfIZXNk1Q/edit#gid=0'
  fids1 <- gsheet::gsheet2tbl(fids_url) %>% dplyr::select(bohemia_id, first_name, last_name, supervisor) %>% dplyr::mutate(country = 'Tanzania')
  fids_url <- 'https://docs.google.com/spreadsheets/d/1o1DGtCUrlBZcu-iLW-reWuB3PC8poEFGYxHfIZXNk1Q/edit#gid=490144130'
  fids2 <- gsheet::gsheet2tbl(fids_url) %>% dplyr::select(bohemia_id, first_name, last_name, supervisor) %>% dplyr::mutate(country = 'Mozambique')
  fids_url <- 'https://docs.google.com/spreadsheets/d/1o1DGtCUrlBZcu-iLW-reWuB3PC8poEFGYxHfIZXNk1Q/edit#gid=179257508'
  fids3 <- gsheet::gsheet2tbl(fids_url) %>% dplyr::select(bohemia_id, first_name, last_name, supervisor) %>% dplyr::mutate(country = 'Catalonia')
  fids <- bind_rows(fids1, fids2, fids3)
  readr::write_csv(fids, '/tmp/fids.csv')
} else {
  fids <- readr::read_csv('/tmp/fids.csv')
}
```

```{r}
# get traccar data - one row per ID 
dat <- get_traccar_data(url = creds$traccar_server,
                        user = creds$traccar_user,
                        pass = creds$traccar_pass)
pd <- dat %>%
  mutate(uniqueId = as.numeric(uniqueId)) %>%
  dplyr::arrange(uniqueId) %>%
  dplyr::select(`Bohemia ID` = uniqueId,
                status,
                name,
                lastUpdate)
bohemia::prettify(pd, nrows = nrow(dat),
                  download_options = TRUE)
```

```{r}
traccar1 <- separate(data = traccar, col = 'valid', into = c('battery', 'distance', 'total_distance', 'motion'), sep = ' ')
traccar$battery <- as.numeric(unlist(lapply(strsplit(traccar$battery, ':'), function(x) x[2])))
traccar$distance <- as.numeric(unlist(lapply(strsplit(traccar$distance, ':'), function(x) x[2])))
traccar$total_distance <- as.numeric(unlist(lapply(strsplit(traccar$total_distance, ':'), function(x) x[2])))
traccar$motion <- as.character(unlist(lapply(strsplit(traccar$motion, ':'), function(x) x[2])))


traccar_moz <- traccar %>% filter(unique_id %in% fids$bohemia_id[fids$country == 'Mozambique'])
traccar_tza <- traccar %>% filter(unique_id %in% fids$bohemia_id[fids$country == 'Tanzania'])
```

## Tracking Mozambique

### Aggreage maps
```{r}

# map of all fw
pts = st_as_sf(data.frame(traccar_moz), coords = c("longitude", "latitude"), crs = 4326)
l <- leaflet() %>% 
      addProviderTiles(providers$Esri.WorldImagery)%>%
        addGlPoints(data = pts,
                    fillColor = 'black',
                    popup = pts %>% dplyr::select(devicetime, deviceid),
                    group = "pts")

# map of fw stops over time
l <- leaflet() %>% 
      addProviderTiles(providers$Esri.WorldImagery)%>%
        addGlPoints(data = pts %>% filter(motion=='false'),
                    fillColor = 'black',
                    popup = pts %>% dplyr::select(devicetime, deviceid, motion),
                    group = "pts")

# map of fw by battery
l <- leaflet() %>% 
      addProviderTiles(providers$Esri.WorldImagery)%>%
        addGlPoints(data = pts,
                    fillColor = ~battery,
                    popup = pts %>% dplyr::select(devicetime, deviceid, battery),
                    group = "pts")


```

### Aggregate tables
```{r}
# get dat object using mozambique timezone
traccar_moz$date <- as.Date(traccar_moz$devicetime, "GMT+2")

# groupby date get number of people with their average total disance, battery, and number of stops
moz_tab <- traccar_moz %>% group_by(date) %>% summarise(`Numer of active FW` = n(), `Average total distance traveled` = mean(total_distance, na.rm=TRUE), `Average battery life` = mean(battery, na.rm = TRUE), `Number of stops` = sum(motion=='true'))

# get table
bohemia::prettify(moz_tab, nrows = 10,
                  download_options = TRUE)
```

### Individual maps

```{r}
# examine device id 195
sub_moz <- traccar_moz %>% filter(deviceid=='195')
pts = st_as_sf(data.frame(sub_moz), coords = c("longitude", "latitude"), crs = 4326)

# total movements color by date
l <- leaflet() %>% 
      addProviderTiles(providers$Esri.WorldImagery)%>%
        addGlPoints(data = pts,
                    fillColor = ~date,
                    fillOpacity = 1,
                    popup = pts %>% dplyr::select(devicetime, deviceid,date),
                    group = "pts")
l

# total movements color by battery
l <- leaflet() %>% 
      addProviderTiles(providers$Esri.WorldImagery)%>%
        addGlPoints(data = pts,
                    fillColor = ~battery,
                    fillOpacity = 1,
                    popup = pts %>% dplyr::select(devicetime, deviceid,battery),
                    group = "pts")
l
# total movements color by total distance
l <- leaflet() %>% 
      addProviderTiles(providers$Esri.WorldImagery)%>%
        addGlPoints(data = pts,
                    fillColor = ~total_distance,
                    fillOpacity = 1,
                    popup = pts %>% dplyr::select(devicetime, deviceid,total_distance),
                    group = "pts")
l

# total movements color by stops
l <- leaflet() %>% 
      addProviderTiles(providers$Esri.WorldImagery)%>%
        addGlPoints(data = pts %>% filter(motion='false'),
                    fillColor = ~date,
                    fillOpacity = 1,
                    popup = pts %>% dplyr::select(devicetime, deviceid,date),
                    group = "pts")
l



```