INSERT INTO `locationhierarchy` VALUES ('hierarchy1', 'MOZ', 'Mozambique', 'hierarchyLevelId1', 'hierarchy_root');
INSERT INTO `locationhierarchy` VALUES ('hierarchy2', 'TAN', 'Tanzania', 'hierarchyLevelId1', 'hierarchy_root');
INSERT INTO `locationhierarchy` VALUES ('hierarchy3', 'MOP', 'Mopeia', 'hierarchyLevelId2', 'hierarchy1');
INSERT INTO `locationhierarchy` VALUES ('hierarchy4', 'KIB', 'Kibiti', 'hierarchyLevelId2', 'hierarchy2');
INSERT INTO `locationhierarchy` VALUES ('hierarchy5', 'RUF', 'Rufiji DC', 'hierarchyLevelId2', 'hierarchy2');
INSERT INTO `locationhierarchy` VALUES ('hierarchy6', 'MOE', 'Mopeia Sede', 'hierarchyLevelId3', 'hierarchy3');
INSERT INTO `locationhierarchy` VALUES ('hierarchy7', 'POS', 'Posto Campo', 'hierarchyLevelId3', 'hierarchy3');
INSERT INTO `locationhierarchy` VALUES ('hierarchy8', 'SAM', 'Sambalendo', 'hierarchyLevelId3', 'hierarchy3');
INSERT INTO `locationhierarchy` VALUES ('hierarchy9', 'KII', 'Kibiti', 'hierarchyLevelId3', 'hierarchy4');
INSERT INTO `locationhierarchy` VALUES ('hierarchy10', 'BUN', 'Bungu', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy11', 'CHE', 'Chemchem', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy12', 'CHU', 'Chumbi', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy13', 'DIM', 'Dimani', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy14', 'IKW', 'Ikwiriri', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy15', 'KIO', 'Kiongoroni', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy16', 'KIP', 'Kipugira', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy17', 'MAH', 'Mahege', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy18', 'MAP', 'Maparoni', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy19', 'MBU', 'Mbuchi', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy20', 'MBW', 'Mbwara', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy21', 'MCH', 'Mchukwi', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy22', 'MGO', 'Mgomba', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy23', 'MJA', 'Mjawa', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy24', 'MKO', 'Mkongo', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy25', 'MLA', 'Mlanzi', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy26', 'MOH', 'Mohoro', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy27', 'MSA', 'Msala', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy28', 'MTA', 'Mtawanya', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy29', 'MTU', 'Mtunda', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy30', 'MWA', 'Mwambao', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy31', 'MWM', 'Mwaseni', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy32', 'NGA', 'Ngarambe', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy33', 'NGO', 'Ngorongo', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy34', 'RUA', 'Ruaruke', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy35', 'SAL', 'Salale', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy36', 'UMW', 'Umwe', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy37', 'UTE', 'Utete', 'hierarchyLevelId3', 'hierarchy5');
INSERT INTO `locationhierarchy` VALUES ('hierarchy38', 'MOD', 'Mopeia Sede/Cuacua', 'hierarchyLevelId4', 'hierarchy6');
INSERT INTO `locationhierarchy` VALUES ('hierarchy39', 'ROV', 'Rovuma/Conho', 'hierarchyLevelId4', 'hierarchy6');
INSERT INTO `locationhierarchy` VALUES ('hierarchy40', 'CAM', 'Campo Sede', 'hierarchyLevelId4', 'hierarchy7');
INSERT INTO `locationhierarchy` VALUES ('hierarchy41', 'CAT', 'Catale', 'hierarchyLevelId4', 'hierarchy7');
INSERT INTO `locationhierarchy` VALUES ('hierarchy42', 'LUA', 'Luala', 'hierarchyLevelId4', 'hierarchy7');
INSERT INTO `locationhierarchy` VALUES ('hierarchy43', 'MUN', 'Mungane', 'hierarchyLevelId4', 'hierarchy7');
INSERT INTO `locationhierarchy` VALUES ('hierarchy44', 'CHI', 'Chimuara', 'hierarchyLevelId4', 'hierarchy8');
INSERT INTO `locationhierarchy` VALUES ('hierarchy45', 'NZA', 'Nzanza', 'hierarchyLevelId4', 'hierarchy8');
INSERT INTO `locationhierarchy` VALUES ('hierarchy46', 'NZE', 'Nzero', 'hierarchyLevelId4', 'hierarchy8');
INSERT INTO `locationhierarchy` VALUES ('hierarchy47', 'KIA', 'Kibiti Kati', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy48', 'KIU', 'Kibiti Kusini', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy49', 'KIN', 'Kingwira', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy50', 'KIT', 'Kitembo', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy51', 'MAK', 'Makaoni', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy52', 'MBE', 'Mbebetini', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy53', 'MKU', 'Mkundi', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy54', 'MKA', 'Mkupuka', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy55', 'NYA', 'Nyamakingili', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy56', 'NYN', 'Nyangwego', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy57', 'NYT', 'Nyatanga', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy58', 'RUN', 'Runyozi', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy59', 'SOK', 'Sokoni', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy60', 'ZII', 'Ziimbwini', 'hierarchyLevelId4', 'hierarchy9');
INSERT INTO `locationhierarchy` VALUES ('hierarchy61', 'BUB', 'Bungu "A"', 'hierarchyLevelId4', 'hierarchy10');
INSERT INTO `locationhierarchy` VALUES ('hierarchy62', 'BUU', 'Bungu B', 'hierarchyLevelId4', 'hierarchy10');
INSERT INTO `locationhierarchy` VALUES ('hierarchy63', 'MAN', 'Mangombela', 'hierarchyLevelId4', 'hierarchy10');
INSERT INTO `locationhierarchy` VALUES ('hierarchy64', 'MSF', 'Msafiri', 'hierarchyLevelId4', 'hierarchy10');
INSERT INTO `locationhierarchy` VALUES ('hierarchy65', 'NYL', 'Nyambili', 'hierarchyLevelId4', 'hierarchy10');
INSERT INTO `locationhierarchy` VALUES ('hierarchy66', 'NYB', 'Nyambunda', 'hierarchyLevelId4', 'hierarchy10');
INSERT INTO `locationhierarchy` VALUES ('hierarchy67', 'PAG', 'Pagae', 'hierarchyLevelId4', 'hierarchy10');
INSERT INTO `locationhierarchy` VALUES ('hierarchy68', 'GOL', 'Golani', 'hierarchyLevelId4', 'hierarchy11');
INSERT INTO `locationhierarchy` VALUES ('hierarchy69', 'KID', 'Kindwiti', 'hierarchyLevelId4', 'hierarchy11');
INSERT INTO `locationhierarchy` VALUES ('hierarchy70', 'KIK', 'Kipei', 'hierarchyLevelId4', 'hierarchy11');
INSERT INTO `locationhierarchy` VALUES ('hierarchy71', 'NYU', 'Nyandakatundu', 'hierarchyLevelId4', 'hierarchy11');
INSERT INTO `locationhierarchy` VALUES ('hierarchy72', 'NYD', 'Nyandumbi', 'hierarchyLevelId4', 'hierarchy11');
INSERT INTO `locationhierarchy` VALUES ('hierarchy73', 'NYG', 'Nyangwai', 'hierarchyLevelId4', 'hierarchy11');
INSERT INTO `locationhierarchy` VALUES ('hierarchy74', 'NYE', 'Nyawanje/ngwembele', 'hierarchyLevelId4', 'hierarchy11');
INSERT INTO `locationhierarchy` VALUES ('hierarchy75', 'CH ', 'Chumbi "A"', 'hierarchyLevelId4', 'hierarchy12');
INSERT INTO `locationhierarchy` VALUES ('hierarchy76', 'CHH', 'Chumbi "B"', 'hierarchyLevelId4', 'hierarchy12');
INSERT INTO `locationhierarchy` VALUES ('hierarchy77', 'CH"', 'Chumbi "C"', 'hierarchyLevelId4', 'hierarchy12');
INSERT INTO `locationhierarchy` VALUES ('hierarchy78', 'BON', 'Bondeni', 'hierarchyLevelId4', 'hierarchy13');
INSERT INTO `locationhierarchy` VALUES ('hierarchy79', 'DII', 'Dimani', 'hierarchyLevelId4', 'hierarchy13');
INSERT INTO `locationhierarchy` VALUES ('hierarchy80', 'DIA', 'Dimani A', 'hierarchyLevelId4', 'hierarchy13');
INSERT INTO `locationhierarchy` VALUES ('hierarchy81', 'DI ', 'Dimani B', 'hierarchyLevelId4', 'hierarchy13');
INSERT INTO `locationhierarchy` VALUES ('hierarchy82', 'KIL', 'Kilimbili', 'hierarchyLevelId4', 'hierarchy13');
INSERT INTO `locationhierarchy` VALUES ('hierarchy83', 'KIM', 'Kimbuga', 'hierarchyLevelId4', 'hierarchy13');
INSERT INTO `locationhierarchy` VALUES ('hierarchy84', 'NGM', 'Ng\'ambo', 'hierarchyLevelId4', 'hierarchy13');
INSERT INTO `locationhierarchy` VALUES ('hierarchy85', 'NGU', 'Ngulakula', 'hierarchyLevelId4', 'hierarchy13');
INSERT INTO `locationhierarchy` VALUES ('hierarchy86', 'NYY', 'Nyambangala', 'hierarchyLevelId4', 'hierarchy13');
INSERT INTO `locationhierarchy` VALUES ('hierarchy87', 'PEN', 'Penda', 'hierarchyLevelId4', 'hierarchy13');
INSERT INTO `locationhierarchy` VALUES ('hierarchy88', 'IKI', 'Ikwiriri Kaskazini', 'hierarchyLevelId4', 'hierarchy14');
INSERT INTO `locationhierarchy` VALUES ('hierarchy89', 'IKK', 'Ikwiriri Kati', 'hierarchyLevelId4', 'hierarchy14');
INSERT INTO `locationhierarchy` VALUES ('hierarchy90', 'IKN', 'Ikwiriri Kusini', 'hierarchyLevelId4', 'hierarchy14');
INSERT INTO `locationhierarchy` VALUES ('hierarchy91', 'JAJ', 'Jaja', 'hierarchyLevelId4', 'hierarchy15');
INSERT INTO `locationhierarchy` VALUES ('hierarchy92', 'KIR', 'Kiongoroni', 'hierarchyLevelId4', 'hierarchy15');
INSERT INTO `locationhierarchy` VALUES ('hierarchy93', 'POM', 'Pombwe', 'hierarchyLevelId4', 'hierarchy15');
INSERT INTO `locationhierarchy` VALUES ('hierarchy94', 'RUM', 'Ruma', 'hierarchyLevelId4', 'hierarchy15');
INSERT INTO `locationhierarchy` VALUES ('hierarchy95', 'YJL', 'Kipo', 'hierarchyLevelId4', 'hierarchy16');
INSERT INTO `locationhierarchy` VALUES ('hierarchy96', 'KIG', 'Kipugira', 'hierarchyLevelId4', 'hierarchy16');
INSERT INTO `locationhierarchy` VALUES ('hierarchy97', 'NDU', 'Ndundunyikanza', 'hierarchyLevelId4', 'hierarchy16');
INSERT INTO `locationhierarchy` VALUES ('hierarchy98', 'NYM', 'Nyaminywili', 'hierarchyLevelId4', 'hierarchy16');
INSERT INTO `locationhierarchy` VALUES ('hierarchy99', 'HAN', 'Hanga', 'hierarchyLevelId4', 'hierarchy17');
INSERT INTO `locationhierarchy` VALUES ('hierarchy100', 'MAE', 'Mahege', 'hierarchyLevelId4', 'hierarchy17');
INSERT INTO `locationhierarchy` VALUES ('hierarchy101', 'NYO', 'Nyakinyo', 'hierarchyLevelId4', 'hierarchy17');
INSERT INTO `locationhierarchy` VALUES ('hierarchy102', 'NYJ', 'Nyanjati', 'hierarchyLevelId4', 'hierarchy17');
INSERT INTO `locationhierarchy` VALUES ('hierarchy103', 'TOM', 'Tomoni', 'hierarchyLevelId4', 'hierarchy17');
INSERT INTO `locationhierarchy` VALUES ('hierarchy104', 'KIE', 'Kiechuru', 'hierarchyLevelId4', 'hierarchy18');
INSERT INTO `locationhierarchy` VALUES ('hierarchy105', 'MAA', 'Maparoni', 'hierarchyLevelId4', 'hierarchy18');
INSERT INTO `locationhierarchy` VALUES ('hierarchy106', 'MBM', 'Mbuchi', 'hierarchyLevelId4', 'hierarchy19');
INSERT INTO `locationhierarchy` VALUES ('hierarchy107', 'MBI', 'Mbwera Magharibi', 'hierarchyLevelId4', 'hierarchy19');
INSERT INTO `locationhierarchy` VALUES ('hierarchy108', 'MBR', 'Mbwera Mashariki', 'hierarchyLevelId4', 'hierarchy19');
INSERT INTO `locationhierarchy` VALUES ('hierarchy109', 'SQK', 'Kitapi', 'hierarchyLevelId4', 'hierarchy20');
INSERT INTO `locationhierarchy` VALUES ('hierarchy110', 'MBB', 'Mbwara', 'hierarchyLevelId4', 'hierarchy20');
INSERT INTO `locationhierarchy` VALUES ('hierarchy111', 'NAM', 'Nambunju', 'hierarchyLevelId4', 'hierarchy20');
INSERT INTO `locationhierarchy` VALUES ('hierarchy112', 'NYW', 'Nyamwage', 'hierarchyLevelId4', 'hierarchy20');
INSERT INTO `locationhierarchy` VALUES ('hierarchy113', 'TAW', 'Tawi', 'hierarchyLevelId4', 'hierarchy20');
INSERT INTO `locationhierarchy` VALUES ('hierarchy114', 'MAW', 'Mangwi', 'hierarchyLevelId4', 'hierarchy21');
INSERT INTO `locationhierarchy` VALUES ('hierarchy115', 'MC ', 'Mchukwi A', 'hierarchyLevelId4', 'hierarchy21');
INSERT INTO `locationhierarchy` VALUES ('hierarchy116', 'MCW', 'Mchukwi B', 'hierarchyLevelId4', 'hierarchy21');
INSERT INTO `locationhierarchy` VALUES ('hierarchy117', 'MKM', 'Mkupuka', 'hierarchyLevelId4', 'hierarchy21');
INSERT INTO `locationhierarchy` VALUES ('hierarchy118', 'MGN', 'Mgomba Kaskazini', 'hierarchyLevelId4', 'hierarchy22');
INSERT INTO `locationhierarchy` VALUES ('hierarchy119', 'MGG', 'Mgomba Kati', 'hierarchyLevelId4', 'hierarchy22');
INSERT INTO `locationhierarchy` VALUES ('hierarchy120', 'MGS', 'Mgomba Kusini', 'hierarchyLevelId4', 'hierarchy22');
INSERT INTO `locationhierarchy` VALUES ('hierarchy121', 'JAR', 'Jaribu Magharibi', 'hierarchyLevelId4', 'hierarchy23');
INSERT INTO `locationhierarchy` VALUES ('hierarchy122', 'JAB', 'Jaribu Mpakani', 'hierarchyLevelId4', 'hierarchy23');
INSERT INTO `locationhierarchy` VALUES ('hierarchy123', 'MJM', 'Mjawa', 'hierarchyLevelId4', 'hierarchy23');
INSERT INTO `locationhierarchy` VALUES ('hierarchy124', 'MOT', 'Motomoto', 'hierarchyLevelId4', 'hierarchy23');
INSERT INTO `locationhierarchy` VALUES ('hierarchy125', 'NGL', 'Ngalengwa', 'hierarchyLevelId4', 'hierarchy23');
INSERT INTO `locationhierarchy` VALUES ('hierarchy126', 'UCH', 'Uchembe', 'hierarchyLevelId4', 'hierarchy23');
INSERT INTO `locationhierarchy` VALUES ('hierarchy127', 'UPO', 'Uponda', 'hierarchyLevelId4', 'hierarchy23');
INSERT INTO `locationhierarchy` VALUES ('hierarchy128', 'MB ', 'Mbunju Mvuleni', 'hierarchyLevelId4', 'hierarchy24');
INSERT INTO `locationhierarchy` VALUES ('hierarchy129', 'MKN', 'Mkongo Kaskazini', 'hierarchyLevelId4', 'hierarchy24');
INSERT INTO `locationhierarchy` VALUES ('hierarchy130', 'MKI', 'Mkongo Kusini', 'hierarchyLevelId4', 'hierarchy24');
INSERT INTO `locationhierarchy` VALUES ('hierarchy131', 'RUW', 'Ruwe', 'hierarchyLevelId4', 'hierarchy24');
INSERT INTO `locationhierarchy` VALUES ('hierarchy132', 'MAC', 'Machipi', 'hierarchyLevelId4', 'hierarchy25');
INSERT INTO `locationhierarchy` VALUES ('hierarchy133', 'MLL', 'Mlanzi', 'hierarchyLevelId4', 'hierarchy25');
INSERT INTO `locationhierarchy` VALUES ('hierarchy134', 'NGN', 'Ngondai', 'hierarchyLevelId4', 'hierarchy25');
INSERT INTO `locationhierarchy` VALUES ('hierarchy135', 'NYI', 'Nyamwimbe', 'hierarchyLevelId4', 'hierarchy25');
INSERT INTO `locationhierarchy` VALUES ('hierarchy136', 'OHM', 'King\'ong\'o', 'hierarchyLevelId4', 'hierarchy26');
INSERT INTO `locationhierarchy` VALUES ('hierarchy137', 'KIW', 'Kiwanga', 'hierarchyLevelId4', 'hierarchy26');
INSERT INTO `locationhierarchy` VALUES ('hierarchy138', 'MOI', 'Mohoro Magharibi', 'hierarchyLevelId4', 'hierarchy26');
INSERT INTO `locationhierarchy` VALUES ('hierarchy139', 'MO ', 'Mohoro Mashariki', 'hierarchyLevelId4', 'hierarchy26');
INSERT INTO `locationhierarchy` VALUES ('hierarchy140', 'NDA', 'Ndundutawa', 'hierarchyLevelId4', 'hierarchy26');
INSERT INTO `locationhierarchy` VALUES ('hierarchy141', 'SHE', 'Shela', 'hierarchyLevelId4', 'hierarchy26');
INSERT INTO `locationhierarchy` VALUES ('hierarchy142', 'KIS', 'Kiasi', 'hierarchyLevelId4', 'hierarchy27');
INSERT INTO `locationhierarchy` VALUES ('hierarchy143', 'MSM', 'Msala', 'hierarchyLevelId4', 'hierarchy27');
INSERT INTO `locationhierarchy` VALUES ('hierarchy144', 'TWA', 'Twasalie', 'hierarchyLevelId4', 'hierarchy27');
INSERT INTO `locationhierarchy` VALUES ('hierarchy145', 'BUM', 'Bumba', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy146', 'KIY', 'Kinyanya Kati', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy147', 'MAG', 'Magogo matatu', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy148', 'MAT', 'Matumbi', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy149', 'MIK', 'Mikendo', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy150', 'MSO', 'Msoro', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy151', 'NDE', 'Ndechamula', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy152', 'DAJ', 'Nyamlani', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy153', 'ROJ', 'Roja', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy154', 'UGE', 'Ugezi', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy155', 'UMI', 'Umikendo', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy156', 'UMK', 'Umkunama', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy157', 'UPA', 'Upazi', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy158', 'ZOM', 'Zomboko', 'hierarchyLevelId4', 'hierarchy28');
INSERT INTO `locationhierarchy` VALUES ('hierarchy159', 'IVG', 'Kikale', 'hierarchyLevelId4', 'hierarchy29');
INSERT INTO `locationhierarchy` VALUES ('hierarchy160', 'MTN', 'Mtunda A', 'hierarchyLevelId4', 'hierarchy29');
INSERT INTO `locationhierarchy` VALUES ('hierarchy161', 'MTM', 'Mtunda B', 'hierarchyLevelId4', 'hierarchy29');
INSERT INTO `locationhierarchy` VALUES ('hierarchy162', 'MUY', 'Muyuyu', 'hierarchyLevelId4', 'hierarchy29');
INSERT INTO `locationhierarchy` VALUES ('hierarchy163', 'ERM', 'Kigunguli', 'hierarchyLevelId4', 'hierarchy30');
INSERT INTO `locationhierarchy` VALUES ('hierarchy164', 'KIV', 'Kivinja "A"', 'hierarchyLevelId4', 'hierarchy30');
INSERT INTO `locationhierarchy` VALUES ('hierarchy165', 'KIJ', 'Kivinja "B"', 'hierarchyLevelId4', 'hierarchy30');
INSERT INTO `locationhierarchy` VALUES ('hierarchy166', 'MCG', 'Mchungu', 'hierarchyLevelId4', 'hierarchy30');
INSERT INTO `locationhierarchy` VALUES ('hierarchy167', 'MKE', 'Mkenda', 'hierarchyLevelId4', 'hierarchy30');
INSERT INTO `locationhierarchy` VALUES ('hierarchy168', 'MSI', 'Msindaji', 'hierarchyLevelId4', 'hierarchy30');
INSERT INTO `locationhierarchy` VALUES ('hierarchy169', 'MLO', 'Mloka', 'hierarchyLevelId4', 'hierarchy31');
INSERT INTO `locationhierarchy` VALUES ('hierarchy170', 'MT ', 'Mtanza /Msona', 'hierarchyLevelId4', 'hierarchy31');
INSERT INTO `locationhierarchy` VALUES ('hierarchy171', 'MWS', 'Mwaseni', 'hierarchyLevelId4', 'hierarchy31');
INSERT INTO `locationhierarchy` VALUES ('hierarchy172', 'KUN', 'Kungulwe', 'hierarchyLevelId4', 'hierarchy32');
INSERT INTO `locationhierarchy` VALUES ('hierarchy173', 'NAK', 'Namakono', 'hierarchyLevelId4', 'hierarchy32');
INSERT INTO `locationhierarchy` VALUES ('hierarchy174', 'NGR', 'Ngarambe Mashariki', 'hierarchyLevelId4', 'hierarchy32');
INSERT INTO `locationhierarchy` VALUES ('hierarchy175', 'NGG', 'NgarambeMagharibi', 'hierarchyLevelId4', 'hierarchy32');
INSERT INTO `locationhierarchy` VALUES ('hierarchy176', 'TAP', 'Tapika', 'hierarchyLevelId4', 'hierarchy32');
INSERT INTO `locationhierarchy` VALUES ('hierarchy177', 'KI ', 'Kilimani Magharibi', 'hierarchyLevelId4', 'hierarchy33');
INSERT INTO `locationhierarchy` VALUES ('hierarchy178', 'KIH', 'Kilimani Mashariki', 'hierarchyLevelId4', 'hierarchy33');
INSERT INTO `locationhierarchy` VALUES ('hierarchy179', 'NGB', 'Ngorongo Magharibi', 'hierarchyLevelId4', 'hierarchy33');
INSERT INTO `locationhierarchy` VALUES ('hierarchy180', 'NGH', 'Ngorongo Mashariki', 'hierarchyLevelId4', 'hierarchy33');
INSERT INTO `locationhierarchy` VALUES ('hierarchy181', 'VSG', 'Kilulatambwe', 'hierarchyLevelId4', 'hierarchy34');
INSERT INTO `locationhierarchy` VALUES ('hierarchy182', 'TFZ', 'Nyamatanga', 'hierarchyLevelId4', 'hierarchy34');
INSERT INTO `locationhierarchy` VALUES ('hierarchy183', 'RUU', 'Ruaruke', 'hierarchyLevelId4', 'hierarchy34');
INSERT INTO `locationhierarchy` VALUES ('hierarchy184', 'RU ', 'Ruaruke B', 'hierarchyLevelId4', 'hierarchy34');
INSERT INTO `locationhierarchy` VALUES ('hierarchy185', 'RUR', 'Rungungu', 'hierarchyLevelId4', 'hierarchy34');
INSERT INTO `locationhierarchy` VALUES ('hierarchy186', 'CSP', 'Kiomboni', 'hierarchyLevelId4', 'hierarchy35');
INSERT INTO `locationhierarchy` VALUES ('hierarchy187', 'MCA', 'Mchinga', 'hierarchyLevelId4', 'hierarchy35');
INSERT INTO `locationhierarchy` VALUES ('hierarchy188', 'MFI', 'Mfisini', 'hierarchyLevelId4', 'hierarchy35');
INSERT INTO `locationhierarchy` VALUES ('hierarchy189', 'NYS', 'Nyamisati', 'hierarchyLevelId4', 'hierarchy35');
INSERT INTO `locationhierarchy` VALUES ('hierarchy190', 'UMN', 'Umwe Kaskazini', 'hierarchyLevelId4', 'hierarchy36');
INSERT INTO `locationhierarchy` VALUES ('hierarchy191', 'UMA', 'Umwe Kati', 'hierarchyLevelId4', 'hierarchy36');
INSERT INTO `locationhierarchy` VALUES ('hierarchy192', 'UM ', 'Umwe Kusini', 'hierarchyLevelId4', 'hierarchy36');
INSERT INTO `locationhierarchy` VALUES ('hierarchy193', 'KFG', 'Kitundu', 'hierarchyLevelId4', 'hierarchy37');
INSERT INTO `locationhierarchy` VALUES ('hierarchy194', 'TXL', 'Kiwili', 'hierarchyLevelId4', 'hierarchy37');
INSERT INTO `locationhierarchy` VALUES ('hierarchy195', 'SIA', 'Siasa', 'hierarchyLevelId4', 'hierarchy37');
INSERT INTO `locationhierarchy` VALUES ('hierarchy196', '24 ', '24 de Julho', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy197', '25 ', '25 de Junho', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy198', '4 D', '4 de Outubro', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy199', '7 D', '7 de Abril', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy200', '8 D', '8 de Marco', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy201', 'ALF', 'Alfredo', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy202', 'AMB', 'Ambrosio', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy203', 'ARM', 'Armando Emilio Guebuza', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy204', 'BAT', 'Batelao', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy205', 'BEN', 'Benejoaque', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy206', 'CAP', 'Capece', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy207', 'CHO', 'Chicote', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy208', 'CHM', 'Chimpene', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy209', 'CHQ', 'Chitequeteque', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy210', 'CHC', 'Chiverano', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy211', 'CHZ', 'Chizimba', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy212', 'CHN', 'Chunga', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy213', 'CIM', 'Cimento', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy214', 'COC', 'Cocorico', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy215', 'CUN', 'Cunhanhassa', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy216', 'DAN', 'Dande', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy217', 'DAA', 'Danhau', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy218', 'DOM', 'Dombe/Balame', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy219', 'EDU', 'Eduardo Mondlane', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy220', 'FOR', 'Forca da Mudanca', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy221', 'GAL', 'Gale', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy222', 'GON', 'Gonda', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy223', 'JOS', 'Josina Machel', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy224', 'LIB', 'Liberdade A', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy225', 'LIR', 'Liberdade B', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy226', 'LUT', 'Luta Continua', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy227', 'MAB', 'Magamba', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy228', 'MAL', 'Malulo', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy229', 'MAM', 'Mangala', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy230', 'MAZ', 'Mazembe', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy231', 'MIF', 'Mifarinha', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy232', 'MIG', 'Migoa', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy233', 'MOC', 'Mocha', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy234', 'MUG', 'Mugurrumba Sede', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy235', 'MUL', 'Mulaira', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy236', 'MUR', 'Muriwa', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy237', 'MUT', 'Muto', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy238', 'NDI', 'Ndima Mangaze', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy239', 'NHA', 'Nhalumbanda', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy240', 'NHN', 'Nhamissundo', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy241', 'NHH', 'Nhanga', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy242', 'NOR', 'Norte', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy243', 'NOT', 'Nota', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy244', 'NSA', 'Nsadgi', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy245', 'NSS', 'Nsando', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy246', 'NTA', 'Ntada', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy247', 'POO', 'Posso', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy248', 'SAB', 'Sabesse', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy249', 'SAE', 'Samurendje', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy250', 'SER', 'Serracao', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy251', 'TAM', 'Tambalico', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy252', 'TES', 'Tesoura', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy253', 'TEW', 'Tewe', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy254', 'TIQ', 'Tiquita', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy255', 'VEM', 'Vembe', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy256', 'VUM', 'Vumbe', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy257', 'XAM', 'Xamanga/Bone', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy258', 'ZON', 'Zona Verde', 'hierarchyLevelId5', 'hierarchy38');
INSERT INTO `locationhierarchy` VALUES ('hierarchy259', 'ALD', 'Alfredo', 'hierarchyLevelId5', 'hierarchy39');
INSERT INTO `locationhierarchy` VALUES ('hierarchy260', 'CUM', 'Cumbalenga', 'hierarchyLevelId5', 'hierarchy39');
INSERT INTO `locationhierarchy` VALUES ('hierarchy261', 'LOT', 'Lota', 'hierarchyLevelId5', 'hierarchy39');
INSERT INTO `locationhierarchy` VALUES ('hierarchy262', 'MAJ', 'Majambe', 'hierarchyLevelId5', 'hierarchy39');
INSERT INTO `locationhierarchy` VALUES ('hierarchy263', 'NHO', 'Nhango', 'hierarchyLevelId5', 'hierarchy39');
INSERT INTO `locationhierarchy` VALUES ('hierarchy264', 'NSN', 'Nsanzo', 'hierarchyLevelId5', 'hierarchy39');
INSERT INTO `locationhierarchy` VALUES ('hierarchy265', 'NTR', 'Ntruzao', 'hierarchyLevelId5', 'hierarchy39');
INSERT INTO `locationhierarchy` VALUES ('hierarchy266', '1 D', '1 de Maio', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy267', '25U', '25 de Junho', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy268', '252', '25 de Setembro', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy269', '3 D', '3 de Fevereiro', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy270', '4 R', '4 de Outubro', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy271', 'ACO', 'Acordos de Lusaka', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy272', 'ARO', 'Armando Emilio Guebuza', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy273', 'ASS', 'Assiate', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy274', 'BAJ', 'Bajone', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy275', 'BAR', 'Bariela', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy276', 'CAI', 'Caixote', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy277', 'CUD', 'Cundine', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy278', 'EDA', 'Eduardo Mondlane', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy279', 'JOR', 'Jorissa', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy280', 'JO ', 'Josina Machel', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy281', 'MAI', 'Maina', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy282', 'MIL', 'Milange', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy283', 'NAA', 'Namitala', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy284', 'NTX', 'Ntxenga', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy285', 'SAC', 'Sacuane', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy286', 'SAR', 'Samaral', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy287', 'SOL', 'Sololo', 'hierarchyLevelId5', 'hierarchy40');
INSERT INTO `locationhierarchy` VALUES ('hierarchy288', 'AND', 'Andale', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy289', 'ANT', 'Antonio', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy290', 'CHA', 'Changaue', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy291', 'LIC', 'Licasse', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy292', 'GLB', 'Manhai', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy293', 'MBA', 'Mbawala', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy294', 'MOR', 'Morais', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy295', 'MUA', 'Muacaniua', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy296', 'MUU', 'Murrongone', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy297', 'NAR', 'Namaria', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy298', 'NHG', 'Nhagoanine', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy299', 'PAN', 'Panela', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy300', 'RAP', 'Raposo', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy301', 'WAL', 'Waluto', 'hierarchyLevelId5', 'hierarchy41');
INSERT INTO `locationhierarchy` VALUES ('hierarchy302', '1 1', '1 de Junho', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy303', '1 I', '1 de Maio', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy304', '255', '25 de Junho', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy305', '3  ', '3 de Fevereiro', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy306', '7 I', '7 de Abril', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy307', 'ACK', 'Acordos de Lusaka', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy308', 'CAD', 'Cadongo', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy309', 'CAL', 'Caline', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy310', 'CET', 'Ceta', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy311', 'CHR', 'Chiurine', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy312', 'LID', 'Liberdade', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy313', 'LIM', 'Lima', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy314', 'MAU', 'Mauia', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy315', 'MIC', 'Micombezi', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy316', 'MIR', 'Mirrongone', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy317', 'MPI', 'Mpiaeca', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy318', 'MUD', 'Mudiba', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy319', 'NAS', 'Nasarone', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy320', 'NHR', 'Nhamirimba', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy321', 'PAZ', 'Paz', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy322', 'RIM', 'Rimba', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy323', 'SIM', 'Simogo', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy324', 'SIT', 'Sitone', 'hierarchyLevelId5', 'hierarchy42');
INSERT INTO `locationhierarchy` VALUES ('hierarchy325', 'COM', 'Compone', 'hierarchyLevelId5', 'hierarchy43');
INSERT INTO `locationhierarchy` VALUES ('hierarchy326', 'GUI', 'Guia', 'hierarchyLevelId5', 'hierarchy43');
INSERT INTO `locationhierarchy` VALUES ('hierarchy327', 'LUU', 'Luala', 'hierarchyLevelId5', 'hierarchy43');
INSERT INTO `locationhierarchy` VALUES ('hierarchy328', 'MIM', 'Micajune', 'hierarchyLevelId5', 'hierarchy43');
INSERT INTO `locationhierarchy` VALUES ('hierarchy329', 'MIP', 'Mipurene', 'hierarchyLevelId5', 'hierarchy43');
INSERT INTO `locationhierarchy` VALUES ('hierarchy330', 'MII', 'Mirerene', 'hierarchyLevelId5', 'hierarchy43');
INSERT INTO `locationhierarchy` VALUES ('hierarchy331', 'MUM', 'Muanamaino', 'hierarchyLevelId5', 'hierarchy43');
INSERT INTO `locationhierarchy` VALUES ('hierarchy332', 'NAL', 'Namicole', 'hierarchyLevelId5', 'hierarchy43');
INSERT INTO `locationhierarchy` VALUES ('hierarchy333', 'PAM', 'Pambane', 'hierarchyLevelId5', 'hierarchy43');
INSERT INTO `locationhierarchy` VALUES ('hierarchy334', 'VAR', 'Vareia', 'hierarchyLevelId5', 'hierarchy43');
INSERT INTO `locationhierarchy` VALUES ('hierarchy335', 'ZEN', 'Zengue', 'hierarchyLevelId5', 'hierarchy43');
INSERT INTO `locationhierarchy` VALUES ('hierarchy336', '1 E', '1 de Maio', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy337', '25E', '25 de Setembro', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy338', '3 R', '3 de Fevereiro', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy339', '7  ', '7 de Setembro', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy340', 'ACE', 'Acordos de Lusaka', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy341', 'ARA', 'Armando Emilio Guebuza', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy342', 'BRA', 'Braz', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy343', 'CHS', 'Chimuara Sede', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy344', 'CHB', 'Chizimba', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy345', 'COY', 'Coyowe', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy346', 'EDE', 'Eduardo Mondlane', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy347', 'FAR', 'Fardo', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy348', 'JOJ', 'Josina Machel', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy349', 'JUL', 'Julius Nyerere', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy350', 'LII', 'Liberdade', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy351', 'MAO', 'Magaio', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy352', 'BTX', 'Mambucha', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy353', 'MAD', 'Mandawa', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy354', 'MEF', 'Mefula', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy355', 'MIN', 'Minjale', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy356', 'NHC', 'Nhacatundo', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy357', 'NHM', 'Nhamizinga', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy358', 'NOE', 'Noere', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy359', 'QUE', 'Quembo', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy360', 'SAS', 'Sambalendo', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy361', 'SAO', 'Samora Machel', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy362', 'SAN', 'Sangate', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy363', 'SAA', 'Sassune', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy364', 'SOA', 'Soares', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy365', 'SOM', 'Somopo', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy366', 'TAI', 'Taibo', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy367', 'VAL', 'Valeta', 'hierarchyLevelId5', 'hierarchy44');
INSERT INTO `locationhierarchy` VALUES ('hierarchy368', 'JAN', 'Janeiro', 'hierarchyLevelId5', 'hierarchy45');
INSERT INTO `locationhierarchy` VALUES ('hierarchy369', 'NHE', 'Nhamirere', 'hierarchyLevelId5', 'hierarchy45');
INSERT INTO `locationhierarchy` VALUES ('hierarchy370', 'RUO', 'Nhanga', 'hierarchyLevelId5', 'hierarchy45');
INSERT INTO `locationhierarchy` VALUES ('hierarchy371', 'NZS', 'Nzanza Sede', 'hierarchyLevelId5', 'hierarchy45');
INSERT INTO `locationhierarchy` VALUES ('hierarchy372', '25M', '25 de Setembro', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy373', 'AGO', 'Agostinho Neto', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy374', 'CHT', 'Chitucotuco', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy375', 'CIC', 'Cimento', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy376', 'EDL', 'Eduardo Mondlane', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy377', 'GUL', 'Gulamo', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy378', 'LIA', 'Liberdade', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy379', 'NAO', 'Namigonhane', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy380', 'NAV', 'Navena', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy381', 'NCO', 'Ncomati', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy382', 'NHL', 'Nhamingulo', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy383', 'NHI', 'Nhamipama', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy384', 'NSU', 'Nsussa', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy385', 'MZE', 'Sambane', 'hierarchyLevelId5', 'hierarchy46');
INSERT INTO `locationhierarchy` VALUES ('hierarchy386', 'QVE', 'Kibiti Kati', 'hierarchyLevelId5', 'hierarchy47');
INSERT INTO `locationhierarchy` VALUES ('hierarchy387', 'WQY', 'Kibiti Kusini', 'hierarchyLevelId5', 'hierarchy48');
INSERT INTO `locationhierarchy` VALUES ('hierarchy388', 'ARQ', 'Kingwira', 'hierarchyLevelId5', 'hierarchy49');
INSERT INTO `locationhierarchy` VALUES ('hierarchy389', 'OYX', 'Kitembo', 'hierarchyLevelId5', 'hierarchy50');
INSERT INTO `locationhierarchy` VALUES ('hierarchy390', 'WDV', 'Makaoni', 'hierarchyLevelId5', 'hierarchy51');
INSERT INTO `locationhierarchy` VALUES ('hierarchy391', 'MBN', 'Mbebetini', 'hierarchyLevelId5', 'hierarchy52');
INSERT INTO `locationhierarchy` VALUES ('hierarchy392', 'MKD', 'Mkundi', 'hierarchyLevelId5', 'hierarchy53');
INSERT INTO `locationhierarchy` VALUES ('hierarchy393', 'MKP', 'Mkupuka', 'hierarchyLevelId5', 'hierarchy54');
INSERT INTO `locationhierarchy` VALUES ('hierarchy394', 'NYK', 'Nyamakingili', 'hierarchyLevelId5', 'hierarchy55');
INSERT INTO `locationhierarchy` VALUES ('hierarchy395', 'XLV', 'Nyangwego', 'hierarchyLevelId5', 'hierarchy56');
INSERT INTO `locationhierarchy` VALUES ('hierarchy396', 'LCX', 'Nyatanga', 'hierarchyLevelId5', 'hierarchy57');
INSERT INTO `locationhierarchy` VALUES ('hierarchy397', 'RUI', 'Runyozi', 'hierarchyLevelId5', 'hierarchy58');
INSERT INTO `locationhierarchy` VALUES ('hierarchy398', 'SOO', 'Sokoni', 'hierarchyLevelId5', 'hierarchy59');
INSERT INTO `locationhierarchy` VALUES ('hierarchy399', 'ZIW', 'Ziimbwini', 'hierarchyLevelId5', 'hierarchy60');
INSERT INTO `locationhierarchy` VALUES ('hierarchy400', 'MKK', 'Mkundi', 'hierarchyLevelId5', 'hierarchy61');
INSERT INTO `locationhierarchy` VALUES ('hierarchy401', 'MWE', 'Mwenge', 'hierarchyLevelId5', 'hierarchy61');
INSERT INTO `locationhierarchy` VALUES ('hierarchy402', 'MWO', 'Mwongozo', 'hierarchyLevelId5', 'hierarchy61');
INSERT INTO `locationhierarchy` VALUES ('hierarchy403', 'OIZ', 'Nyamango', 'hierarchyLevelId5', 'hierarchy61');
INSERT INTO `locationhierarchy` VALUES ('hierarchy404', 'FRX', 'Kibaoni', 'hierarchyLevelId5', 'hierarchy62');
INSERT INTO `locationhierarchy` VALUES ('hierarchy405', 'DTN', 'Kibwibwi', 'hierarchyLevelId5', 'hierarchy62');
INSERT INTO `locationhierarchy` VALUES ('hierarchy406', 'SVW', 'Kinyamale', 'hierarchyLevelId5', 'hierarchy62');
INSERT INTO `locationhierarchy` VALUES ('hierarchy407', 'OPQ', 'Kipenya', 'hierarchyLevelId5', 'hierarchy62');
INSERT INTO `locationhierarchy` VALUES ('hierarchy408', 'EPT', 'Kitula', 'hierarchyLevelId5', 'hierarchy62');
INSERT INTO `locationhierarchy` VALUES ('hierarchy409', 'AZI', 'Azimio', 'hierarchyLevelId5', 'hierarchy63');
INSERT INTO `locationhierarchy` VALUES ('hierarchy410', 'PGJ', 'Nyamango', 'hierarchyLevelId5', 'hierarchy63');
INSERT INTO `locationhierarchy` VALUES ('hierarchy411', 'BU ', 'Bungu \'B\'', 'hierarchyLevelId5', 'hierarchy64');
INSERT INTO `locationhierarchy` VALUES ('hierarchy412', 'MSS', 'Msafiri', 'hierarchyLevelId5', 'hierarchy64');
INSERT INTO `locationhierarchy` VALUES ('hierarchy413', 'NGK', 'Ngongoloka', 'hierarchyLevelId5', 'hierarchy64');
INSERT INTO `locationhierarchy` VALUES ('hierarchy414', 'TSG', 'Nyakilo', 'hierarchyLevelId5', 'hierarchy64');
INSERT INTO `locationhierarchy` VALUES ('hierarchy415', 'ZUM', 'Zumbe', 'hierarchyLevelId5', 'hierarchy64');
INSERT INTO `locationhierarchy` VALUES ('hierarchy416', 'DUN', 'Dungutu', 'hierarchyLevelId5', 'hierarchy65');
INSERT INTO `locationhierarchy` VALUES ('hierarchy417', 'NYZ', 'Nyambili Kaskazini', 'hierarchyLevelId5', 'hierarchy65');
INSERT INTO `locationhierarchy` VALUES ('hierarchy418', 'NY ', 'Nyambili Kusini', 'hierarchyLevelId5', 'hierarchy65');
INSERT INTO `locationhierarchy` VALUES ('hierarchy419', 'BES', 'Besabu', 'hierarchyLevelId5', 'hierarchy66');
INSERT INTO `locationhierarchy` VALUES ('hierarchy420', 'MKW', 'Mkwandara', 'hierarchyLevelId5', 'hierarchy66');
INSERT INTO `locationhierarchy` VALUES ('hierarchy421', 'NAN', 'Nangundu', 'hierarchyLevelId5', 'hierarchy66');
INSERT INTO `locationhierarchy` VALUES ('hierarchy422', 'LUG', 'Lugome', 'hierarchyLevelId5', 'hierarchy67');
INSERT INTO `locationhierarchy` VALUES ('hierarchy423', 'MKL', 'Mkale', 'hierarchyLevelId5', 'hierarchy67');
INSERT INTO `locationhierarchy` VALUES ('hierarchy424', 'HGJ', 'Nyameku', 'hierarchyLevelId5', 'hierarchy67');
INSERT INTO `locationhierarchy` VALUES ('hierarchy425', 'UND', 'Undembo', 'hierarchyLevelId5', 'hierarchy67');
INSERT INTO `locationhierarchy` VALUES ('hierarchy426', 'GOA', 'Golani', 'hierarchyLevelId5', 'hierarchy68');
INSERT INTO `locationhierarchy` VALUES ('hierarchy427', 'PXL', 'Kindwiti', 'hierarchyLevelId5', 'hierarchy69');
INSERT INTO `locationhierarchy` VALUES ('hierarchy428', 'AEG', 'Kipei', 'hierarchyLevelId5', 'hierarchy70');
INSERT INTO `locationhierarchy` VALUES ('hierarchy429', 'KEN', 'Nyandakatundu', 'hierarchyLevelId5', 'hierarchy71');
INSERT INTO `locationhierarchy` VALUES ('hierarchy430', 'ICM', 'Nyandumbi', 'hierarchyLevelId5', 'hierarchy72');
INSERT INTO `locationhierarchy` VALUES ('hierarchy431', 'WDH', 'Nyangwai', 'hierarchyLevelId5', 'hierarchy73');
INSERT INTO `locationhierarchy` VALUES ('hierarchy432', 'DBJ', 'Nyawanje/ngwembele', 'hierarchyLevelId5', 'hierarchy74');
INSERT INTO `locationhierarchy` VALUES ('hierarchy433', 'IPE', 'Ipengo', 'hierarchyLevelId5', 'hierarchy75');
INSERT INTO `locationhierarchy` VALUES ('hierarchy434', 'STL', 'Kiegele', 'hierarchyLevelId5', 'hierarchy75');
INSERT INTO `locationhierarchy` VALUES ('hierarchy435', 'RQH', 'Kigogo', 'hierarchyLevelId5', 'hierarchy75');
INSERT INTO `locationhierarchy` VALUES ('hierarchy436', 'TAA', 'Tangini', 'hierarchyLevelId5', 'hierarchy75');
INSERT INTO `locationhierarchy` VALUES ('hierarchy437', 'ZSA', 'Kilindi', 'hierarchyLevelId5', 'hierarchy76');
INSERT INTO `locationhierarchy` VALUES ('hierarchy438', 'STV', 'Kipoka', 'hierarchyLevelId5', 'hierarchy76');
INSERT INTO `locationhierarchy` VALUES ('hierarchy439', 'YJS', 'Kipoka msomeni', 'hierarchyLevelId5', 'hierarchy76');
INSERT INTO `locationhierarchy` VALUES ('hierarchy440', 'MIA', 'Mikorwa', 'hierarchyLevelId5', 'hierarchy76');
INSERT INTO `locationhierarchy` VALUES ('hierarchy441', 'MSN', 'Msikitini', 'hierarchyLevelId5', 'hierarchy76');
INSERT INTO `locationhierarchy` VALUES ('hierarchy442', 'MFD', 'Chumbi Magharibi', 'hierarchyLevelId5', 'hierarchy77');
INSERT INTO `locationhierarchy` VALUES ('hierarchy443', 'KAN', 'Kanga', 'hierarchyLevelId5', 'hierarchy77');
INSERT INTO `locationhierarchy` VALUES ('hierarchy444', 'HBS', 'Ngaro', 'hierarchyLevelId5', 'hierarchy77');
INSERT INTO `locationhierarchy` VALUES ('hierarchy445', 'NYP', 'Nyakipande', 'hierarchyLevelId5', 'hierarchy77');
INSERT INTO `locationhierarchy` VALUES ('hierarchy446', 'BOD', 'Bondeni', 'hierarchyLevelId5', 'hierarchy78');
INSERT INTO `locationhierarchy` VALUES ('hierarchy447', 'DID', 'Dimani', 'hierarchyLevelId5', 'hierarchy79');
INSERT INTO `locationhierarchy` VALUES ('hierarchy448', 'DIN', 'Dimani A', 'hierarchyLevelId5', 'hierarchy80');
INSERT INTO `locationhierarchy` VALUES ('hierarchy449', 'DIB', 'Dimani B', 'hierarchyLevelId5', 'hierarchy81');
INSERT INTO `locationhierarchy` VALUES ('hierarchy450', 'HRM', 'Kilimbili', 'hierarchyLevelId5', 'hierarchy82');
INSERT INTO `locationhierarchy` VALUES ('hierarchy451', 'MSQ', 'Kimbuga', 'hierarchyLevelId5', 'hierarchy83');
INSERT INTO `locationhierarchy` VALUES ('hierarchy452', 'YRL', 'Ng\'ambo', 'hierarchyLevelId5', 'hierarchy84');
INSERT INTO `locationhierarchy` VALUES ('hierarchy453', 'PNJ', 'Ngulakula', 'hierarchyLevelId5', 'hierarchy85');
INSERT INTO `locationhierarchy` VALUES ('hierarchy454', 'ZAD', 'Nyambangala', 'hierarchyLevelId5', 'hierarchy86');
INSERT INTO `locationhierarchy` VALUES ('hierarchy455', 'PED', 'Penda', 'hierarchyLevelId5', 'hierarchy87');
INSERT INTO `locationhierarchy` VALUES ('hierarchy456', 'KAU', 'Kaunda', 'hierarchyLevelId5', 'hierarchy88');
INSERT INTO `locationhierarchy` VALUES ('hierarchy457', 'KAZ', 'Kazamoyo', 'hierarchyLevelId5', 'hierarchy88');
INSERT INTO `locationhierarchy` VALUES ('hierarchy458', 'MPA', 'Mparange', 'hierarchyLevelId5', 'hierarchy88');
INSERT INTO `locationhierarchy` VALUES ('hierarchy459', 'MTJ', 'Mtakuja', 'hierarchyLevelId5', 'hierarchy88');
INSERT INTO `locationhierarchy` VALUES ('hierarchy460', 'MWG', 'Mwenge', 'hierarchyLevelId5', 'hierarchy88');
INSERT INTO `locationhierarchy` VALUES ('hierarchy461', 'UJA', 'Ujamaa', 'hierarchyLevelId5', 'hierarchy88');
INSERT INTO `locationhierarchy` VALUES ('hierarchy462', 'MSK', 'Msikitini', 'hierarchyLevelId5', 'hierarchy89');
INSERT INTO `locationhierarchy` VALUES ('hierarchy463', 'MWN', 'Mwenge', 'hierarchyLevelId5', 'hierarchy89');
INSERT INTO `locationhierarchy` VALUES ('hierarchy464', 'SID', 'SIDO', 'hierarchyLevelId5', 'hierarchy89');
INSERT INTO `locationhierarchy` VALUES ('hierarchy465', 'SIS', 'Sisi kwa Sisi', 'hierarchyLevelId5', 'hierarchy89');
INSERT INTO `locationhierarchy` VALUES ('hierarchy466', 'TAT', 'Tangimoja', 'hierarchyLevelId5', 'hierarchy89');
INSERT INTO `locationhierarchy` VALUES ('hierarchy467', 'UJI', 'Ujirani Mwema', 'hierarchyLevelId5', 'hierarchy89');
INSERT INTO `locationhierarchy` VALUES ('hierarchy468', 'UMO', 'Umoja', 'hierarchyLevelId5', 'hierarchy89');
INSERT INTO `locationhierarchy` VALUES ('hierarchy469', 'UPE', 'Upendo', 'hierarchyLevelId5', 'hierarchy89');
INSERT INTO `locationhierarchy` VALUES ('hierarchy470', 'KAR', 'Karume', 'hierarchyLevelId5', 'hierarchy90');
INSERT INTO `locationhierarchy` VALUES ('hierarchy471', 'KAW', 'Kawawa', 'hierarchyLevelId5', 'hierarchy90');
INSERT INTO `locationhierarchy` VALUES ('hierarchy472', 'FSG', 'Malemba', 'hierarchyLevelId5', 'hierarchy90');
INSERT INTO `locationhierarchy` VALUES ('hierarchy473', 'MPP', 'Mpima', 'hierarchyLevelId5', 'hierarchy90');
INSERT INTO `locationhierarchy` VALUES ('hierarchy474', 'MUO', 'Muungano', 'hierarchyLevelId5', 'hierarchy90');
INSERT INTO `locationhierarchy` VALUES ('hierarchy475', 'NYR', 'Nyerere', 'hierarchyLevelId5', 'hierarchy90');
INSERT INTO `locationhierarchy` VALUES ('hierarchy476', 'P/K', 'P/Kisumo', 'hierarchyLevelId5', 'hierarchy90');
INSERT INTO `locationhierarchy` VALUES ('hierarchy477', 'POT', 'Posta', 'hierarchyLevelId5', 'hierarchy90');
INSERT INTO `locationhierarchy` VALUES ('hierarchy478', 'TA ', 'Tangimbili Kusini', 'hierarchyLevelId5', 'hierarchy90');
INSERT INTO `locationhierarchy` VALUES ('hierarchy479', 'UHU', 'Uhuru', 'hierarchyLevelId5', 'hierarchy90');
INSERT INTO `locationhierarchy` VALUES ('hierarchy480', 'UJJ', 'Ujamaa', 'hierarchyLevelId5', 'hierarchy90');
INSERT INTO `locationhierarchy` VALUES ('hierarchy481', 'BUA', 'Bumbuamani', 'hierarchyLevelId5', 'hierarchy91');
INSERT INTO `locationhierarchy` VALUES ('hierarchy482', 'FID', 'Kitongani', 'hierarchyLevelId5', 'hierarchy91');
INSERT INTO `locationhierarchy` VALUES ('hierarchy483', 'MJI', 'Mjimwema', 'hierarchyLevelId5', 'hierarchy91');
INSERT INTO `locationhierarchy` VALUES ('hierarchy484', 'BWE', 'Bweni', 'hierarchyLevelId5', 'hierarchy92');
INSERT INTO `locationhierarchy` VALUES ('hierarchy485', 'BIT', 'Makwende', 'hierarchyLevelId5', 'hierarchy92');
INSERT INTO `locationhierarchy` VALUES ('hierarchy486', 'RGW', 'Nyaobe', 'hierarchyLevelId5', 'hierarchy92');
INSERT INTO `locationhierarchy` VALUES ('hierarchy487', 'EBK', 'Kilambani', 'hierarchyLevelId5', 'hierarchy93');
INSERT INTO `locationhierarchy` VALUES ('hierarchy488', 'MBG', 'Mbungwi', 'hierarchyLevelId5', 'hierarchy93');
INSERT INTO `locationhierarchy` VALUES ('hierarchy489', 'POE', 'Pombwe kubwa', 'hierarchyLevelId5', 'hierarchy93');
INSERT INTO `locationhierarchy` VALUES ('hierarchy490', 'SUN', 'Suni', 'hierarchyLevelId5', 'hierarchy93');
INSERT INTO `locationhierarchy` VALUES ('hierarchy491', 'BAN', 'Bandarini', 'hierarchyLevelId5', 'hierarchy94');
INSERT INTO `locationhierarchy` VALUES ('hierarchy492', 'EME', 'Emelwa', 'hierarchyLevelId5', 'hierarchy94');
INSERT INTO `locationhierarchy` VALUES ('hierarchy493', 'YXM', 'King\'ongo', 'hierarchyLevelId5', 'hierarchy94');
INSERT INTO `locationhierarchy` VALUES ('hierarchy494', 'MTT', 'Mtanga', 'hierarchyLevelId5', 'hierarchy94');
INSERT INTO `locationhierarchy` VALUES ('hierarchy495', 'FGT', 'Nyamikamba', 'hierarchyLevelId5', 'hierarchy94');
INSERT INTO `locationhierarchy` VALUES ('hierarchy496', 'IBT', 'Mawilo', 'hierarchyLevelId5', 'hierarchy95');
INSERT INTO `locationhierarchy` VALUES ('hierarchy497', 'MGH', 'Mgohori', 'hierarchyLevelId5', 'hierarchy95');
INSERT INTO `locationhierarchy` VALUES ('hierarchy498', 'MPE', 'Mpande', 'hierarchyLevelId5', 'hierarchy95');
INSERT INTO `locationhierarchy` VALUES ('hierarchy499', 'YHT', 'Nyikanza', 'hierarchyLevelId5', 'hierarchy95');
INSERT INTO `locationhierarchy` VALUES ('hierarchy500', 'LSI', 'Kipugira', 'hierarchyLevelId5', 'hierarchy96');
INSERT INTO `locationhierarchy` VALUES ('hierarchy501', 'PAP', 'Pangapanga', 'hierarchyLevelId5', 'hierarchy96');
INSERT INTO `locationhierarchy` VALUES ('hierarchy502', 'TET', 'Tetema', 'hierarchyLevelId5', 'hierarchy97');
INSERT INTO `locationhierarchy` VALUES ('hierarchy503', 'MTL', 'Mtalula', 'hierarchyLevelId5', 'hierarchy98');
INSERT INTO `locationhierarchy` VALUES ('hierarchy504', 'GOV', 'Nyaminywili', 'hierarchyLevelId5', 'hierarchy98');
INSERT INTO `locationhierarchy` VALUES ('hierarchy505', 'NQK', 'Kimbogo', 'hierarchyLevelId5', 'hierarchy99');
INSERT INTO `locationhierarchy` VALUES ('hierarchy506', 'ONB', 'Mkima', 'hierarchyLevelId5', 'hierarchy99');
INSERT INTO `locationhierarchy` VALUES ('hierarchy507', 'NGE', 'Ngambe', 'hierarchyLevelId5', 'hierarchy99');
INSERT INTO `locationhierarchy` VALUES ('hierarchy508', 'BVP', 'Nyambwanda', 'hierarchyLevelId5', 'hierarchy99');
INSERT INTO `locationhierarchy` VALUES ('hierarchy509', 'ZEH', 'Mawichi', 'hierarchyLevelId5', 'hierarchy100');
INSERT INTO `locationhierarchy` VALUES ('hierarchy510', 'MTB', 'Mtambwe', 'hierarchyLevelId5', 'hierarchy100');
INSERT INTO `locationhierarchy` VALUES ('hierarchy511', 'PRZ', 'Nyamkingia', 'hierarchyLevelId5', 'hierarchy100');
INSERT INTO `locationhierarchy` VALUES ('hierarchy512', 'UMB', 'Umba', 'hierarchyLevelId5', 'hierarchy100');
INSERT INTO `locationhierarchy` VALUES ('hierarchy513', 'NGD', 'Ngondae/Mlete', 'hierarchyLevelId5', 'hierarchy101');
INSERT INTO `locationhierarchy` VALUES ('hierarchy514', 'SOS', 'Soso/Nyakinyo', 'hierarchyLevelId5', 'hierarchy101');
INSERT INTO `locationhierarchy` VALUES ('hierarchy515', 'VKR', 'Mapinduzi', 'hierarchyLevelId5', 'hierarchy102');
INSERT INTO `locationhierarchy` VALUES ('hierarchy516', 'MRE', 'Mrema', 'hierarchyLevelId5', 'hierarchy102');
INSERT INTO `locationhierarchy` VALUES ('hierarchy517', 'MWI', 'Mwinyi', 'hierarchyLevelId5', 'hierarchy102');
INSERT INTO `locationhierarchy` VALUES ('hierarchy518', 'QTF', 'Nyerere', 'hierarchyLevelId5', 'hierarchy102');
INSERT INTO `locationhierarchy` VALUES ('hierarchy519', 'SAU', 'Saudia', 'hierarchyLevelId5', 'hierarchy102');
INSERT INTO `locationhierarchy` VALUES ('hierarchy520', 'SOI', 'Sokoine', 'hierarchyLevelId5', 'hierarchy102');
INSERT INTO `locationhierarchy` VALUES ('hierarchy521', 'HAL', 'Halisi', 'hierarchyLevelId5', 'hierarchy103');
INSERT INTO `locationhierarchy` VALUES ('hierarchy522', 'MIB', 'Mibuyusaba', 'hierarchyLevelId5', 'hierarchy103');
INSERT INTO `locationhierarchy` VALUES ('hierarchy523', 'WHO', 'Mkali', 'hierarchyLevelId5', 'hierarchy103');
INSERT INTO `locationhierarchy` VALUES ('hierarchy524', 'ZUD', 'Nyakikongo', 'hierarchyLevelId5', 'hierarchy103');
INSERT INTO `locationhierarchy` VALUES ('hierarchy525', 'KAT', 'Kati', 'hierarchyLevelId5', 'hierarchy104');
INSERT INTO `locationhierarchy` VALUES ('hierarchy526', 'KEW', 'Kityanga', 'hierarchyLevelId5', 'hierarchy104');
INSERT INTO `locationhierarchy` VALUES ('hierarchy527', 'KOR', 'Korongo', 'hierarchyLevelId5', 'hierarchy104');
INSERT INTO `locationhierarchy` VALUES ('hierarchy528', 'MGA', 'Mgambo', 'hierarchyLevelId5', 'hierarchy104');
INSERT INTO `locationhierarchy` VALUES ('hierarchy529', 'GIN', 'Gingi', 'hierarchyLevelId5', 'hierarchy105');
INSERT INTO `locationhierarchy` VALUES ('hierarchy530', 'KUD', 'Mbangani', 'hierarchyLevelId5', 'hierarchy105');
INSERT INTO `locationhierarchy` VALUES ('hierarchy531', 'TUW', 'Tuwa', 'hierarchyLevelId5', 'hierarchy105');
INSERT INTO `locationhierarchy` VALUES ('hierarchy532', 'USI', 'Usimbe kiwanjani', 'hierarchyLevelId5', 'hierarchy105');
INSERT INTO `locationhierarchy` VALUES ('hierarchy533', 'USS', 'Usimbekidoga', 'hierarchyLevelId5', 'hierarchy105');
INSERT INTO `locationhierarchy` VALUES ('hierarchy534', 'BAI', 'Barabarani', 'hierarchyLevelId5', 'hierarchy106');
INSERT INTO `locationhierarchy` VALUES ('hierarchy535', 'YPA', 'Kipoka', 'hierarchyLevelId5', 'hierarchy106');
INSERT INTO `locationhierarchy` VALUES ('hierarchy536', 'BWL', 'Kitingi', 'hierarchyLevelId5', 'hierarchy106');
INSERT INTO `locationhierarchy` VALUES ('hierarchy537', 'MAR', 'Makongoro', 'hierarchyLevelId5', 'hierarchy106');
INSERT INTO `locationhierarchy` VALUES ('hierarchy538', 'MIO', 'Mikwang\'ombe', 'hierarchyLevelId5', 'hierarchy106');
INSERT INTO `locationhierarchy` VALUES ('hierarchy539', 'MNG', 'Mnganje', 'hierarchyLevelId5', 'hierarchy106');
INSERT INTO `locationhierarchy` VALUES ('hierarchy540', 'DOK', 'Doka', 'hierarchyLevelId5', 'hierarchy107');
INSERT INTO `locationhierarchy` VALUES ('hierarchy541', 'JBP', 'Kibumburu', 'hierarchyLevelId5', 'hierarchy107');
INSERT INTO `locationhierarchy` VALUES ('hierarchy542', 'WRF', 'Kiiongoro', 'hierarchyLevelId5', 'hierarchy107');
INSERT INTO `locationhierarchy` VALUES ('hierarchy543', 'KUM', 'Kumbacha', 'hierarchyLevelId5', 'hierarchy107');
INSERT INTO `locationhierarchy` VALUES ('hierarchy544', 'KDG', 'Mkepa', 'hierarchyLevelId5', 'hierarchy107');
INSERT INTO `locationhierarchy` VALUES ('hierarchy545', 'MKR', 'Mkurumu', 'hierarchyLevelId5', 'hierarchy107');
INSERT INTO `locationhierarchy` VALUES ('hierarchy546', 'MTW', 'Mtawatawa', 'hierarchyLevelId5', 'hierarchy107');
INSERT INTO `locationhierarchy` VALUES ('hierarchy547', 'FVC', 'Marongoni', 'hierarchyLevelId5', 'hierarchy108');
INSERT INTO `locationhierarchy` VALUES ('hierarchy548', 'DFK', 'Mbumburu', 'hierarchyLevelId5', 'hierarchy108');
INSERT INTO `locationhierarchy` VALUES ('hierarchy549', 'MDA', 'Mdai', 'hierarchyLevelId5', 'hierarchy108');
INSERT INTO `locationhierarchy` VALUES ('hierarchy550', 'AYJ', 'Mkirika', 'hierarchyLevelId5', 'hierarchy108');
INSERT INTO `locationhierarchy` VALUES ('hierarchy551', 'JQH', 'Kitapi Magharibi', 'hierarchyLevelId5', 'hierarchy109');
INSERT INTO `locationhierarchy` VALUES ('hierarchy552', 'LBI', 'Kitapi Mashariki', 'hierarchyLevelId5', 'hierarchy109');
INSERT INTO `locationhierarchy` VALUES ('hierarchy553', 'NAB', 'Namahamba', 'hierarchyLevelId5', 'hierarchy109');
INSERT INTO `locationhierarchy` VALUES ('hierarchy554', 'MBH', 'Mbwara magharibi', 'hierarchyLevelId5', 'hierarchy110');
INSERT INTO `locationhierarchy` VALUES ('hierarchy555', 'MBK', 'Mbwara Mashariki', 'hierarchyLevelId5', 'hierarchy110');
INSERT INTO `locationhierarchy` VALUES ('hierarchy556', 'MIS', 'Misimbo', 'hierarchyLevelId5', 'hierarchy110');
INSERT INTO `locationhierarchy` VALUES ('hierarchy557', 'QRZ', 'Kikibu', 'hierarchyLevelId5', 'hierarchy111');
INSERT INTO `locationhierarchy` VALUES ('hierarchy558', 'MIY', 'Miangalaya', 'hierarchyLevelId5', 'hierarchy111');
INSERT INTO `locationhierarchy` VALUES ('hierarchy559', 'MTK', 'Namakono', 'hierarchyLevelId5', 'hierarchy111');
INSERT INTO `locationhierarchy` VALUES ('hierarchy560', 'NAI', 'Nambunju Magharibi', 'hierarchyLevelId5', 'hierarchy111');
INSERT INTO `locationhierarchy` VALUES ('hierarchy561', 'NAU', 'Nambunju mashariki', 'hierarchyLevelId5', 'hierarchy111');
INSERT INTO `locationhierarchy` VALUES ('hierarchy562', 'NYH', 'Nyamwage Magharibi', 'hierarchyLevelId5', 'hierarchy112');
INSERT INTO `locationhierarchy` VALUES ('hierarchy563', 'ZBF', 'Nyamwage Mashariki', 'hierarchyLevelId5', 'hierarchy112');
INSERT INTO `locationhierarchy` VALUES ('hierarchy564', 'SHA', 'Shauri  moyo', 'hierarchyLevelId5', 'hierarchy112');
INSERT INTO `locationhierarchy` VALUES ('hierarchy565', 'GEG', 'Gege', 'hierarchyLevelId5', 'hierarchy113');
INSERT INTO `locationhierarchy` VALUES ('hierarchy566', 'BHC', 'Kikobo', 'hierarchyLevelId5', 'hierarchy113');
INSERT INTO `locationhierarchy` VALUES ('hierarchy567', 'DLX', 'Mkukiki', 'hierarchyLevelId5', 'hierarchy113');
INSERT INTO `locationhierarchy` VALUES ('hierarchy568', 'VRC', 'Mkwiri', 'hierarchyLevelId5', 'hierarchy113');
INSERT INTO `locationhierarchy` VALUES ('hierarchy569', 'AYW', 'Misimbo', 'hierarchyLevelId5', 'hierarchy114');
INSERT INTO `locationhierarchy` VALUES ('hierarchy570', 'MNY', 'Mnyongoya', 'hierarchyLevelId5', 'hierarchy114');
INSERT INTO `locationhierarchy` VALUES ('hierarchy571', 'RON', 'Rondo', 'hierarchyLevelId5', 'hierarchy114');
INSERT INTO `locationhierarchy` VALUES ('hierarchy572', 'QWK', 'Matimbwani', 'hierarchyLevelId5', 'hierarchy115');
INSERT INTO `locationhierarchy` VALUES ('hierarchy573', 'FBD', 'Nyakaumbanga', 'hierarchyLevelId5', 'hierarchy115');
INSERT INTO `locationhierarchy` VALUES ('hierarchy574', 'UDE', 'Nyamanjenga', 'hierarchyLevelId5', 'hierarchy115');
INSERT INTO `locationhierarchy` VALUES ('hierarchy575', 'UJO', 'Ujongoni', 'hierarchyLevelId5', 'hierarchy115');
INSERT INTO `locationhierarchy` VALUES ('hierarchy576', 'UKI', 'Ukitomondo', 'hierarchyLevelId5', 'hierarchy115');
INSERT INTO `locationhierarchy` VALUES ('hierarchy577', 'KIC', 'Kichangani', 'hierarchyLevelId5', 'hierarchy116');
INSERT INTO `locationhierarchy` VALUES ('hierarchy578', 'MBD', 'Mbinda', 'hierarchyLevelId5', 'hierarchy116');
INSERT INTO `locationhierarchy` VALUES ('hierarchy579', 'MIE', 'Miembeni', 'hierarchyLevelId5', 'hierarchy116');
INSERT INTO `locationhierarchy` VALUES ('hierarchy580', 'XSQ', 'Msikitini', 'hierarchyLevelId5', 'hierarchy116');
INSERT INTO `locationhierarchy` VALUES ('hierarchy581', 'YCU', 'Nyaubi', 'hierarchyLevelId5', 'hierarchy116');
INSERT INTO `locationhierarchy` VALUES ('hierarchy582', 'SON', 'Songa', 'hierarchyLevelId5', 'hierarchy116');
INSERT INTO `locationhierarchy` VALUES ('hierarchy583', 'BAB', 'Bani', 'hierarchyLevelId5', 'hierarchy54');
INSERT INTO `locationhierarchy` VALUES ('hierarchy584', 'GLT', 'Mkupuka', 'hierarchyLevelId5', 'hierarchy54');
INSERT INTO `locationhierarchy` VALUES ('hierarchy585', 'ZSU', 'Nyunga', 'hierarchyLevelId5', 'hierarchy54');
INSERT INTO `locationhierarchy` VALUES ('hierarchy586', 'JIT', 'Jitegemee', 'hierarchyLevelId5', 'hierarchy118');
INSERT INTO `locationhierarchy` VALUES ('hierarchy587', 'MPM', 'Mpima', 'hierarchyLevelId5', 'hierarchy118');
INSERT INTO `locationhierarchy` VALUES ('hierarchy588', 'SEK', 'Sekondari', 'hierarchyLevelId5', 'hierarchy118');
INSERT INTO `locationhierarchy` VALUES ('hierarchy589', 'UJM', 'Ujamaa', 'hierarchyLevelId5', 'hierarchy118');
INSERT INTO `locationhierarchy` VALUES ('hierarchy590', 'ULN', 'Kiapo', 'hierarchyLevelId5', 'hierarchy119');
INSERT INTO `locationhierarchy` VALUES ('hierarchy591', 'ODZ', 'Malenda', 'hierarchyLevelId5', 'hierarchy119');
INSERT INTO `locationhierarchy` VALUES ('hierarchy592', 'MAS', 'Masenda', 'hierarchyLevelId5', 'hierarchy119');
INSERT INTO `locationhierarchy` VALUES ('hierarchy593', 'MTP', 'Mtupa', 'hierarchyLevelId5', 'hierarchy119');
INSERT INTO `locationhierarchy` VALUES ('hierarchy594', 'IAB', 'Kijonjo', 'hierarchyLevelId5', 'hierarchy120');
INSERT INTO `locationhierarchy` VALUES ('hierarchy595', 'CYL', 'Kingwande', 'hierarchyLevelId5', 'hierarchy120');
INSERT INTO `locationhierarchy` VALUES ('hierarchy596', 'YLB', 'Malipia', 'hierarchyLevelId5', 'hierarchy120');
INSERT INTO `locationhierarchy` VALUES ('hierarchy597', 'NON', 'Nongwa', 'hierarchyLevelId5', 'hierarchy120');
INSERT INTO `locationhierarchy` VALUES ('hierarchy598', 'JIW', 'Jiweni', 'hierarchyLevelId5', 'hierarchy121');
INSERT INTO `locationhierarchy` VALUES ('hierarchy599', 'DQG', 'Kibuyuni', 'hierarchyLevelId5', 'hierarchy121');
INSERT INTO `locationhierarchy` VALUES ('hierarchy600', 'AFN', 'Mapinduzi', 'hierarchyLevelId5', 'hierarchy121');
INSERT INTO `locationhierarchy` VALUES ('hierarchy601', 'MKG', 'Mkongoni', 'hierarchyLevelId5', 'hierarchy121');
INSERT INTO `locationhierarchy` VALUES ('hierarchy602', 'MIW', 'Mikwala', 'hierarchyLevelId5', 'hierarchy122');
INSERT INTO `locationhierarchy` VALUES ('hierarchy603', 'MOO', 'Motomoto', 'hierarchyLevelId5', 'hierarchy122');
INSERT INTO `locationhierarchy` VALUES ('hierarchy604', 'MTD', 'Mtunda', 'hierarchyLevelId5', 'hierarchy122');
INSERT INTO `locationhierarchy` VALUES ('hierarchy605', 'PIR', 'Muungano', 'hierarchyLevelId5', 'hierarchy122');
INSERT INTO `locationhierarchy` VALUES ('hierarchy606', 'UJU', 'Ujamaa', 'hierarchyLevelId5', 'hierarchy122');
INSERT INTO `locationhierarchy` VALUES ('hierarchy607', 'BOB', 'Bonjo', 'hierarchyLevelId5', 'hierarchy123');
INSERT INTO `locationhierarchy` VALUES ('hierarchy608', 'DUT', 'Dutani', 'hierarchyLevelId5', 'hierarchy123');
INSERT INTO `locationhierarchy` VALUES ('hierarchy609', 'GOS', 'Gosa', 'hierarchyLevelId5', 'hierarchy123');
INSERT INTO `locationhierarchy` VALUES ('hierarchy610', 'MTE', 'Mtetani', 'hierarchyLevelId5', 'hierarchy123');
INSERT INTO `locationhierarchy` VALUES ('hierarchy611', 'NGW', 'Ngalemwa', 'hierarchyLevelId5', 'hierarchy123');
INSERT INTO `locationhierarchy` VALUES ('hierarchy612', 'GOG', 'Goloatanga', 'hierarchyLevelId5', 'hierarchy124');
INSERT INTO `locationhierarchy` VALUES ('hierarchy613', 'FRY', 'Misogole', 'hierarchyLevelId5', 'hierarchy124');
INSERT INTO `locationhierarchy` VALUES ('hierarchy614', 'MSE', 'Msega', 'hierarchyLevelId5', 'hierarchy125');
INSERT INTO `locationhierarchy` VALUES ('hierarchy615', 'RJM', 'Mtuluma', 'hierarchyLevelId5', 'hierarchy125');
INSERT INTO `locationhierarchy` VALUES ('hierarchy616', 'UCM', 'Uchembe chini', 'hierarchyLevelId5', 'hierarchy126');
INSERT INTO `locationhierarchy` VALUES ('hierarchy617', 'UCU', 'Uchembe juu', 'hierarchyLevelId5', 'hierarchy126');
INSERT INTO `locationhierarchy` VALUES ('hierarchy618', 'UCB', 'Uchembe', 'hierarchyLevelId5', 'hierarchy127');
INSERT INTO `locationhierarchy` VALUES ('hierarchy619', 'UPP', 'Uponda Chini', 'hierarchyLevelId5', 'hierarchy127');
INSERT INTO `locationhierarchy` VALUES ('hierarchy620', 'UPU', 'Uponda Juu', 'hierarchyLevelId5', 'hierarchy127');
INSERT INTO `locationhierarchy` VALUES ('hierarchy621', 'WFT', 'Mbunju', 'hierarchyLevelId5', 'hierarchy128');
INSERT INTO `locationhierarchy` VALUES ('hierarchy622', 'MVU', 'Mvuleni', 'hierarchyLevelId5', 'hierarchy128');
INSERT INTO `locationhierarchy` VALUES ('hierarchy623', 'KAA', 'Karakana', 'hierarchyLevelId5', 'hierarchy129');
INSERT INTO `locationhierarchy` VALUES ('hierarchy624', 'KBC', 'Nyipara', 'hierarchyLevelId5', 'hierarchy129');
INSERT INTO `locationhierarchy` VALUES ('hierarchy625', 'RUS', 'Rusende', 'hierarchyLevelId5', 'hierarchy129');
INSERT INTO `locationhierarchy` VALUES ('hierarchy626', 'LND', 'Kitundu', 'hierarchyLevelId5', 'hierarchy130');
INSERT INTO `locationhierarchy` VALUES ('hierarchy627', 'AUI', 'Kiwili', 'hierarchyLevelId5', 'hierarchy130');
INSERT INTO `locationhierarchy` VALUES ('hierarchy628', 'KMX', 'Makoge', 'hierarchyLevelId5', 'hierarchy130');
INSERT INTO `locationhierarchy` VALUES ('hierarchy629', 'UWE', 'Mkunga', 'hierarchyLevelId5', 'hierarchy130');
INSERT INTO `locationhierarchy` VALUES ('hierarchy630', 'BET', 'Beta', 'hierarchyLevelId5', 'hierarchy131');
INSERT INTO `locationhierarchy` VALUES ('hierarchy631', 'TNP', 'Kipera', 'hierarchyLevelId5', 'hierarchy131');
INSERT INTO `locationhierarchy` VALUES ('hierarchy632', 'NBZ', 'Nyaringwe', 'hierarchyLevelId5', 'hierarchy131');
INSERT INTO `locationhierarchy` VALUES ('hierarchy633', 'PEF', 'Kibuni', 'hierarchyLevelId5', 'hierarchy132');
INSERT INTO `locationhierarchy` VALUES ('hierarchy634', 'EMS', 'Mangimbwage', 'hierarchyLevelId5', 'hierarchy132');
INSERT INTO `locationhierarchy` VALUES ('hierarchy635', 'MST', 'Msikitini', 'hierarchyLevelId5', 'hierarchy132');
INSERT INTO `locationhierarchy` VALUES ('hierarchy636', 'NGJ', 'Ngonja', 'hierarchyLevelId5', 'hierarchy132');
INSERT INTO `locationhierarchy` VALUES ('hierarchy637', 'RUD', 'Ruanda', 'hierarchyLevelId5', 'hierarchy132');
INSERT INTO `locationhierarchy` VALUES ('hierarchy638', 'BOR', 'Bora', 'hierarchyLevelId5', 'hierarchy133');
INSERT INTO `locationhierarchy` VALUES ('hierarchy639', 'PFJ', 'Kikimbili', 'hierarchyLevelId5', 'hierarchy133');
INSERT INTO `locationhierarchy` VALUES ('hierarchy640', 'QJU', 'Kimbindu', 'hierarchyLevelId5', 'hierarchy133');
INSERT INTO `locationhierarchy` VALUES ('hierarchy641', 'NUJ', 'Kingweti', 'hierarchyLevelId5', 'hierarchy133');
INSERT INTO `locationhierarchy` VALUES ('hierarchy642', 'LIK', 'Like', 'hierarchyLevelId5', 'hierarchy133');
INSERT INTO `locationhierarchy` VALUES ('hierarchy643', 'MIZ', 'Milonzi', 'hierarchyLevelId5', 'hierarchy133');
INSERT INTO `locationhierarchy` VALUES ('hierarchy644', 'MKJ', 'Mkwajuni', 'hierarchyLevelId5', 'hierarchy133');
INSERT INTO `locationhierarchy` VALUES ('hierarchy645', 'MLM', 'Mlanzi Magharibi', 'hierarchyLevelId5', 'hierarchy133');
INSERT INTO `locationhierarchy` VALUES ('hierarchy646', 'MLS', 'Mlanzi Mashariki', 'hierarchyLevelId5', 'hierarchy133');
INSERT INTO `locationhierarchy` VALUES ('hierarchy647', 'BOA', 'Bora', 'hierarchyLevelId5', 'hierarchy134');
INSERT INTO `locationhierarchy` VALUES ('hierarchy648', 'INK', 'Kilonji', 'hierarchyLevelId5', 'hierarchy134');
INSERT INTO `locationhierarchy` VALUES ('hierarchy649', 'NGI', 'Ngondai', 'hierarchyLevelId5', 'hierarchy134');
INSERT INTO `locationhierarchy` VALUES ('hierarchy650', 'UVC', 'Malenda', 'hierarchyLevelId5', 'hierarchy135');
INSERT INTO `locationhierarchy` VALUES ('hierarchy651', 'MA ', 'Malenda Halisi', 'hierarchyLevelId5', 'hierarchy135');
INSERT INTO `locationhierarchy` VALUES ('hierarchy652', 'CBS', 'Miparani', 'hierarchyLevelId5', 'hierarchy135');
INSERT INTO `locationhierarchy` VALUES ('hierarchy653', 'JQS', 'Nyelelo', 'hierarchyLevelId5', 'hierarchy135');
INSERT INTO `locationhierarchy` VALUES ('hierarchy654', 'UMT', 'Umtanga', 'hierarchyLevelId5', 'hierarchy135');
INSERT INTO `locationhierarchy` VALUES ('hierarchy655', 'CHY', 'Chayonge', 'hierarchyLevelId5', 'hierarchy136');
INSERT INTO `locationhierarchy` VALUES ('hierarchy656', 'GMP', 'King\'ong\'o', 'hierarchyLevelId5', 'hierarchy136');
INSERT INTO `locationhierarchy` VALUES ('hierarchy657', 'UKM', 'Kisangi', 'hierarchyLevelId5', 'hierarchy136');
INSERT INTO `locationhierarchy` VALUES ('hierarchy658', 'KWA', 'Kwampakwila', 'hierarchyLevelId5', 'hierarchy136');
INSERT INTO `locationhierarchy` VALUES ('hierarchy659', 'MPL', 'Mpelepele', 'hierarchyLevelId5', 'hierarchy136');
INSERT INTO `locationhierarchy` VALUES ('hierarchy660', 'ZHP', 'Kiwanga', 'hierarchyLevelId5', 'hierarchy137');
INSERT INTO `locationhierarchy` VALUES ('hierarchy661', 'LON', 'Londondo', 'hierarchyLevelId5', 'hierarchy137');
INSERT INTO `locationhierarchy` VALUES ('hierarchy662', 'MIH', 'Mihiru', 'hierarchyLevelId5', 'hierarchy137');
INSERT INTO `locationhierarchy` VALUES ('hierarchy663', 'MWW', 'Mwanani', 'hierarchyLevelId5', 'hierarchy138');
INSERT INTO `locationhierarchy` VALUES ('hierarchy664', 'EXC', 'Nyakikai', 'hierarchyLevelId5', 'hierarchy138');
INSERT INTO `locationhierarchy` VALUES ('hierarchy665', 'ALE', 'Nyandote', 'hierarchyLevelId5', 'hierarchy138');
INSERT INTO `locationhierarchy` VALUES ('hierarchy666', 'OLD', 'Oldmohoro', 'hierarchyLevelId5', 'hierarchy138');
INSERT INTO `locationhierarchy` VALUES ('hierarchy667', 'SUG', 'Sunga', 'hierarchyLevelId5', 'hierarchy138');
INSERT INTO `locationhierarchy` VALUES ('hierarchy668', 'SUU', 'Sungapwani', 'hierarchyLevelId5', 'hierarchy138');
INSERT INTO `locationhierarchy` VALUES ('hierarchy669', 'CHW', 'Chamwenge', 'hierarchyLevelId5', 'hierarchy139');
INSERT INTO `locationhierarchy` VALUES ('hierarchy670', 'NUH', 'Nyampaku bara', 'hierarchyLevelId5', 'hierarchy139');
INSERT INTO `locationhierarchy` VALUES ('hierarchy671', 'QYZ', 'Nyampaku mashariki', 'hierarchyLevelId5', 'hierarchy139');
INSERT INTO `locationhierarchy` VALUES ('hierarchy672', 'BSR', 'Nyampaku pwani', 'hierarchyLevelId5', 'hierarchy139');
INSERT INTO `locationhierarchy` VALUES ('hierarchy673', 'ZGO', 'Nyautika', 'hierarchyLevelId5', 'hierarchy139');
INSERT INTO `locationhierarchy` VALUES ('hierarchy674', 'MKZ', 'Mkenzi', 'hierarchyLevelId5', 'hierarchy140');
INSERT INTO `locationhierarchy` VALUES ('hierarchy675', 'TWI', 'Msikitini', 'hierarchyLevelId5', 'hierarchy140');
INSERT INTO `locationhierarchy` VALUES ('hierarchy676', 'NDD', 'Ndundutawa', 'hierarchyLevelId5', 'hierarchy140');
INSERT INTO `locationhierarchy` VALUES ('hierarchy677', 'WZI', 'Nyalindi', 'hierarchyLevelId5', 'hierarchy140');
INSERT INTO `locationhierarchy` VALUES ('hierarchy678', 'RNQ', 'Kindwitwi', 'hierarchyLevelId5', 'hierarchy141');
INSERT INTO `locationhierarchy` VALUES ('hierarchy679', 'RAN', 'Rangitatu', 'hierarchyLevelId5', 'hierarchy141');
INSERT INTO `locationhierarchy` VALUES ('hierarchy680', 'STA', 'Staand Mikolwa', 'hierarchyLevelId5', 'hierarchy141');
INSERT INTO `locationhierarchy` VALUES ('hierarchy681', 'NUN', 'Nunu', 'hierarchyLevelId5', 'hierarchy142');
INSERT INTO `locationhierarchy` VALUES ('hierarchy682', 'HKE', 'Nyunguni', 'hierarchyLevelId5', 'hierarchy142');
INSERT INTO `locationhierarchy` VALUES ('hierarchy683', 'PLO', 'Plot', 'hierarchyLevelId5', 'hierarchy142');
INSERT INTO `locationhierarchy` VALUES ('hierarchy684', 'UWA', 'Uwandani', 'hierarchyLevelId5', 'hierarchy142');
INSERT INTO `locationhierarchy` VALUES ('hierarchy685', 'ZDM', 'Majaliwa', 'hierarchyLevelId5', 'hierarchy143');
INSERT INTO `locationhierarchy` VALUES ('hierarchy686', 'MBL', 'Mbaleni', 'hierarchyLevelId5', 'hierarchy143');
INSERT INTO `locationhierarchy` VALUES ('hierarchy687', 'MBO', 'Mbomboni', 'hierarchyLevelId5', 'hierarchy143');
INSERT INTO `locationhierarchy` VALUES ('hierarchy688', 'UKO', 'Ukongoro', 'hierarchyLevelId5', 'hierarchy143');
INSERT INTO `locationhierarchy` VALUES ('hierarchy689', 'WAS', 'Wasamade', 'hierarchyLevelId5', 'hierarchy143');
INSERT INTO `locationhierarchy` VALUES ('hierarchy690', 'DOD', 'Domwe', 'hierarchyLevelId5', 'hierarchy144');
INSERT INTO `locationhierarchy` VALUES ('hierarchy691', 'DUG', 'Kisimbya', 'hierarchyLevelId5', 'hierarchy144');
INSERT INTO `locationhierarchy` VALUES ('hierarchy692', 'DGX', 'Nyahimba', 'hierarchyLevelId5', 'hierarchy144');
INSERT INTO `locationhierarchy` VALUES ('hierarchy693', 'PLP', 'Plot', 'hierarchyLevelId5', 'hierarchy144');
INSERT INTO `locationhierarchy` VALUES ('hierarchy694', 'TAR', 'Taracho', 'hierarchyLevelId5', 'hierarchy144');
INSERT INTO `locationhierarchy` VALUES ('hierarchy695', 'UEF', 'Bumba', 'hierarchyLevelId5', 'hierarchy145');
INSERT INTO `locationhierarchy` VALUES ('hierarchy696', 'HAS', 'Kinyanya Kati', 'hierarchyLevelId5', 'hierarchy146');
INSERT INTO `locationhierarchy` VALUES ('hierarchy697', 'JPT', 'Magogo matatu', 'hierarchyLevelId5', 'hierarchy147');
INSERT INTO `locationhierarchy` VALUES ('hierarchy698', 'DMZ', 'Matumbi', 'hierarchyLevelId5', 'hierarchy148');
INSERT INTO `locationhierarchy` VALUES ('hierarchy699', 'MID', 'Mikendo', 'hierarchyLevelId5', 'hierarchy149');
INSERT INTO `locationhierarchy` VALUES ('hierarchy700', 'MSR', 'Msoro', 'hierarchyLevelId5', 'hierarchy150');
INSERT INTO `locationhierarchy` VALUES ('hierarchy701', 'NDN', 'Ndechamula', 'hierarchyLevelId5', 'hierarchy151');
INSERT INTO `locationhierarchy` VALUES ('hierarchy702', 'YTC', 'Nyamlani', 'hierarchyLevelId5', 'hierarchy152');
INSERT INTO `locationhierarchy` VALUES ('hierarchy703', 'ROR', 'Roja', 'hierarchyLevelId5', 'hierarchy153');
INSERT INTO `locationhierarchy` VALUES ('hierarchy704', 'UGG', 'Ugezi', 'hierarchyLevelId5', 'hierarchy154');
INSERT INTO `locationhierarchy` VALUES ('hierarchy705', 'UMU', 'Umikendo', 'hierarchyLevelId5', 'hierarchy155');
INSERT INTO `locationhierarchy` VALUES ('hierarchy706', 'UMM', 'Umkunama', 'hierarchyLevelId5', 'hierarchy156');
INSERT INTO `locationhierarchy` VALUES ('hierarchy707', 'UPI', 'Upazi', 'hierarchyLevelId5', 'hierarchy157');
INSERT INTO `locationhierarchy` VALUES ('hierarchy708', 'ZOB', 'Zomboko', 'hierarchyLevelId5', 'hierarchy158');
INSERT INTO `locationhierarchy` VALUES ('hierarchy709', 'YEI', 'Kikale', 'hierarchyLevelId5', 'hierarchy159');
INSERT INTO `locationhierarchy` VALUES ('hierarchy710', 'BSN', 'Kikalemtandu', 'hierarchyLevelId5', 'hierarchy159');
INSERT INTO `locationhierarchy` VALUES ('hierarchy711', 'QGD', 'Makoge', 'hierarchyLevelId5', 'hierarchy159');
INSERT INTO `locationhierarchy` VALUES ('hierarchy712', 'XMA', 'Mbogolo', 'hierarchyLevelId5', 'hierarchy160');
INSERT INTO `locationhierarchy` VALUES ('hierarchy713', 'DPV', 'Mbumi', 'hierarchyLevelId5', 'hierarchy160');
INSERT INTO `locationhierarchy` VALUES ('hierarchy714', 'MIU', 'Mikunguni', 'hierarchyLevelId5', 'hierarchy160');
INSERT INTO `locationhierarchy` VALUES ('hierarchy715', 'EIY', 'Mtunda A', 'hierarchyLevelId5', 'hierarchy160');
INSERT INTO `locationhierarchy` VALUES ('hierarchy716', 'KRZ', 'Nguaro', 'hierarchyLevelId5', 'hierarchy160');
INSERT INTO `locationhierarchy` VALUES ('hierarchy717', 'BEB', 'Beta', 'hierarchyLevelId5', 'hierarchy161');
INSERT INTO `locationhierarchy` VALUES ('hierarchy718', 'MCM', 'Mchikichini', 'hierarchyLevelId5', 'hierarchy161');
INSERT INTO `locationhierarchy` VALUES ('hierarchy719', 'RTK', 'Mtunda B', 'hierarchyLevelId5', 'hierarchy161');
INSERT INTO `locationhierarchy` VALUES ('hierarchy720', 'NGY', 'Nganyaga', 'hierarchyLevelId5', 'hierarchy161');
INSERT INTO `locationhierarchy` VALUES ('hierarchy721', 'NYF', 'Nyafeda', 'hierarchyLevelId5', 'hierarchy161');
INSERT INTO `locationhierarchy` VALUES ('hierarchy722', 'RNA', 'Magomeni', 'hierarchyLevelId5', 'hierarchy162');
INSERT INTO `locationhierarchy` VALUES ('hierarchy723', 'KMC', 'Misuguri', 'hierarchyLevelId5', 'hierarchy162');
INSERT INTO `locationhierarchy` VALUES ('hierarchy724', 'MKT', 'Mkata', 'hierarchyLevelId5', 'hierarchy162');
INSERT INTO `locationhierarchy` VALUES ('hierarchy725', 'IQZ', 'Muyuyu', 'hierarchyLevelId5', 'hierarchy162');
INSERT INTO `locationhierarchy` VALUES ('hierarchy726', 'NJI', 'Njianne', 'hierarchyLevelId5', 'hierarchy162');
INSERT INTO `locationhierarchy` VALUES ('hierarchy727', 'IMT', 'Nyambele', 'hierarchyLevelId5', 'hierarchy162');
INSERT INTO `locationhierarchy` VALUES ('hierarchy728', 'SOE', 'Sonywe', 'hierarchyLevelId5', 'hierarchy162');
INSERT INTO `locationhierarchy` VALUES ('hierarchy729', 'AIB', 'Mkole', 'hierarchyLevelId5', 'hierarchy163');
INSERT INTO `locationhierarchy` VALUES ('hierarchy730', 'MPF', 'Mpafuni', 'hierarchyLevelId5', 'hierarchy163');
INSERT INTO `locationhierarchy` VALUES ('hierarchy731', 'MSL', 'Mselema', 'hierarchyLevelId5', 'hierarchy163');
INSERT INTO `locationhierarchy` VALUES ('hierarchy732', 'KAI', 'Kariakoo', 'hierarchyLevelId5', 'hierarchy164');
INSERT INTO `locationhierarchy` VALUES ('hierarchy733', 'NJD', 'Kigunguli', 'hierarchyLevelId5', 'hierarchy164');
INSERT INTO `locationhierarchy` VALUES ('hierarchy734', 'JWH', 'Kisanjani kaya', 'hierarchyLevelId5', 'hierarchy164');
INSERT INTO `locationhierarchy` VALUES ('hierarchy735', 'EHX', 'Masakwi', 'hierarchyLevelId5', 'hierarchy164');
INSERT INTO `locationhierarchy` VALUES ('hierarchy736', 'MFE', 'Mfenesini', 'hierarchyLevelId5', 'hierarchy165');
INSERT INTO `locationhierarchy` VALUES ('hierarchy737', 'EQM', 'Mkegetoni', 'hierarchyLevelId5', 'hierarchy165');
INSERT INTO `locationhierarchy` VALUES ('hierarchy738', 'MWU', 'Mweyubaruti', 'hierarchyLevelId5', 'hierarchy165');
INSERT INTO `locationhierarchy` VALUES ('hierarchy739', 'MIT', 'Mititimbo', 'hierarchyLevelId5', 'hierarchy166');
INSERT INTO `locationhierarchy` VALUES ('hierarchy740', 'MPK', 'Mpekeso', 'hierarchyLevelId5', 'hierarchy166');
INSERT INTO `locationhierarchy` VALUES ('hierarchy741', 'ECX', 'Kikombe', 'hierarchyLevelId5', 'hierarchy167');
INSERT INTO `locationhierarchy` VALUES ('hierarchy742', 'YSI', 'Mkenda', 'hierarchyLevelId5', 'hierarchy167');
INSERT INTO `locationhierarchy` VALUES ('hierarchy743', 'YLH', 'Ngungule', 'hierarchyLevelId5', 'hierarchy167');
INSERT INTO `locationhierarchy` VALUES ('hierarchy744', 'GEN', 'Genju', 'hierarchyLevelId5', 'hierarchy168');
INSERT INTO `locationhierarchy` VALUES ('hierarchy745', 'HAE', 'Madukani', 'hierarchyLevelId5', 'hierarchy168');
INSERT INTO `locationhierarchy` VALUES ('hierarchy746', 'KWW', 'Kwangazi', 'hierarchyLevelId5', 'hierarchy169');
INSERT INTO `locationhierarchy` VALUES ('hierarchy747', 'LUM', 'Mkange', 'hierarchyLevelId5', 'hierarchy169');
INSERT INTO `locationhierarchy` VALUES ('hierarchy748', 'MPN', 'Mpanganya', 'hierarchyLevelId5', 'hierarchy169');
INSERT INTO `locationhierarchy` VALUES ('hierarchy749', 'XRZ', 'Nyakisiku', 'hierarchyLevelId5', 'hierarchy169');
INSERT INTO `locationhierarchy` VALUES ('hierarchy750', 'BIZ', 'Bizi', 'hierarchyLevelId5', 'hierarchy170');
INSERT INTO `locationhierarchy` VALUES ('hierarchy751', 'MSG', 'Msiga', 'hierarchyLevelId5', 'hierarchy170');
INSERT INTO `locationhierarchy` VALUES ('hierarchy752', 'MTZ', 'Mtanza', 'hierarchyLevelId5', 'hierarchy170');
INSERT INTO `locationhierarchy` VALUES ('hierarchy753', 'MTR', 'Mturuma', 'hierarchyLevelId5', 'hierarchy170');
INSERT INTO `locationhierarchy` VALUES ('hierarchy754', 'VQD', 'Mibuyusaba', 'hierarchyLevelId5', 'hierarchy171');
INSERT INTO `locationhierarchy` VALUES ('hierarchy755', 'YIL', 'Mwaseni', 'hierarchyLevelId5', 'hierarchy171');
INSERT INTO `locationhierarchy` VALUES ('hierarchy756', 'ZOZ', 'Zombe', 'hierarchyLevelId5', 'hierarchy171');
INSERT INTO `locationhierarchy` VALUES ('hierarchy757', 'KUU', 'Kungulwe', 'hierarchyLevelId5', 'hierarchy172');
INSERT INTO `locationhierarchy` VALUES ('hierarchy758', 'GZH', 'Namakono', 'hierarchyLevelId5', 'hierarchy173');
INSERT INTO `locationhierarchy` VALUES ('hierarchy759', 'NG ', 'Ngarambe Mashariki', 'hierarchyLevelId5', 'hierarchy174');
INSERT INTO `locationhierarchy` VALUES ('hierarchy760', 'OIP', 'NgarambeMagharibi', 'hierarchyLevelId5', 'hierarchy175');
INSERT INTO `locationhierarchy` VALUES ('hierarchy761', 'TAK', 'Tapika', 'hierarchyLevelId5', 'hierarchy176');
INSERT INTO `locationhierarchy` VALUES ('hierarchy762', 'YCL', 'Kilombero', 'hierarchyLevelId5', 'hierarchy177');
INSERT INTO `locationhierarchy` VALUES ('hierarchy763', 'NUD', 'Kisagai', 'hierarchyLevelId5', 'hierarchy177');
INSERT INTO `locationhierarchy` VALUES ('hierarchy764', 'MBY', 'Mbuyuni', 'hierarchyLevelId5', 'hierarchy177');
INSERT INTO `locationhierarchy` VALUES ('hierarchy765', 'MPY', 'Mpanganya', 'hierarchyLevelId5', 'hierarchy177');
INSERT INTO `locationhierarchy` VALUES ('hierarchy766', 'TAG', 'Tangini', 'hierarchyLevelId5', 'hierarchy177');
INSERT INTO `locationhierarchy` VALUES ('hierarchy767', 'GEF', 'Gefu', 'hierarchyLevelId5', 'hierarchy178');
INSERT INTO `locationhierarchy` VALUES ('hierarchy768', 'GIY', 'Ginnery', 'hierarchyLevelId5', 'hierarchy178');
INSERT INTO `locationhierarchy` VALUES ('hierarchy769', 'TAJ', 'Mkongeni', 'hierarchyLevelId5', 'hierarchy178');
INSERT INTO `locationhierarchy` VALUES ('hierarchy770', 'TLH', 'Mkunga', 'hierarchyLevelId5', 'hierarchy178');
INSERT INTO `locationhierarchy` VALUES ('hierarchy771', 'UNY', 'Unyonge', 'hierarchyLevelId5', 'hierarchy178');
INSERT INTO `locationhierarchy` VALUES ('hierarchy772', 'GID', 'Kikongono', 'hierarchyLevelId5', 'hierarchy179');
INSERT INTO `locationhierarchy` VALUES ('hierarchy773', 'EHC', 'Nyasungwi', 'hierarchyLevelId5', 'hierarchy179');
INSERT INTO `locationhierarchy` VALUES ('hierarchy774', 'VHS', 'Kipenda moyo', 'hierarchyLevelId5', 'hierarchy180');
INSERT INTO `locationhierarchy` VALUES ('hierarchy775', 'AFW', 'Nyalwiru', 'hierarchyLevelId5', 'hierarchy180');
INSERT INTO `locationhierarchy` VALUES ('hierarchy776', 'CSF', 'Kilulatambwe Kati', 'hierarchyLevelId5', 'hierarchy181');
INSERT INTO `locationhierarchy` VALUES ('hierarchy777', 'MBS', 'Mbusi', 'hierarchyLevelId5', 'hierarchy181');
INSERT INTO `locationhierarchy` VALUES ('hierarchy778', 'XLJ', 'Milonzi', 'hierarchyLevelId5', 'hierarchy181');
INSERT INTO `locationhierarchy` VALUES ('hierarchy779', 'KLE', 'Mkopi', 'hierarchyLevelId5', 'hierarchy182');
INSERT INTO `locationhierarchy` VALUES ('hierarchy780', 'MTO', 'Mtomboloka', 'hierarchyLevelId5', 'hierarchy182');
INSERT INTO `locationhierarchy` VALUES ('hierarchy781', 'NZM', 'Nyamatanga', 'hierarchyLevelId5', 'hierarchy182');
INSERT INTO `locationhierarchy` VALUES ('hierarchy782', 'BPM', 'Kindande', 'hierarchyLevelId5', 'hierarchy183');
INSERT INTO `locationhierarchy` VALUES ('hierarchy783', 'EBV', 'Kiwaga', 'hierarchyLevelId5', 'hierarchy183');
INSERT INTO `locationhierarchy` VALUES ('hierarchy784', 'AYX', 'Mbawa', 'hierarchyLevelId5', 'hierarchy183');
INSERT INTO `locationhierarchy` VALUES ('hierarchy785', 'NFH', 'Mwenge', 'hierarchyLevelId5', 'hierarchy183');
INSERT INTO `locationhierarchy` VALUES ('hierarchy786', 'ZNP', 'Nyambalapi', 'hierarchyLevelId5', 'hierarchy183');
INSERT INTO `locationhierarchy` VALUES ('hierarchy787', 'AAN', 'aangweni Matosa', 'hierarchyLevelId5', 'hierarchy184');
INSERT INTO `locationhierarchy` VALUES ('hierarchy788', 'KIF', 'Kimbwere famiti', 'hierarchyLevelId5', 'hierarchy184');
INSERT INTO `locationhierarchy` VALUES ('hierarchy789', 'MFU', 'Mfule Mkumbini', 'hierarchyLevelId5', 'hierarchy184');
INSERT INTO `locationhierarchy` VALUES ('hierarchy790', 'MGE', 'Mgerezini', 'hierarchyLevelId5', 'hierarchy184');
INSERT INTO `locationhierarchy` VALUES ('hierarchy791', 'NY-', 'Nyanindi - Makoge', 'hierarchyLevelId5', 'hierarchy184');
INSERT INTO `locationhierarchy` VALUES ('hierarchy792', 'GAR', 'Garibovu', 'hierarchyLevelId5', 'hierarchy185');
INSERT INTO `locationhierarchy` VALUES ('hierarchy793', 'WBE', 'Miwaleni', 'hierarchyLevelId5', 'hierarchy185');
INSERT INTO `locationhierarchy` VALUES ('hierarchy794', 'UIG', 'Mkwende', 'hierarchyLevelId5', 'hierarchy185');
INSERT INTO `locationhierarchy` VALUES ('hierarchy795', 'MUW', 'Mungutwa', 'hierarchyLevelId5', 'hierarchy185');
INSERT INTO `locationhierarchy` VALUES ('hierarchy796', 'RUG', 'Rungungu', 'hierarchyLevelId5', 'hierarchy185');
INSERT INTO `locationhierarchy` VALUES ('hierarchy797', 'NLZ', 'Kiomboni Pwani', 'hierarchyLevelId5', 'hierarchy186');
INSERT INTO `locationhierarchy` VALUES ('hierarchy798', 'TWW', 'Twana', 'hierarchyLevelId5', 'hierarchy186');
INSERT INTO `locationhierarchy` VALUES ('hierarchy799', 'URO', 'Urongoni', 'hierarchyLevelId5', 'hierarchy186');
INSERT INTO `locationhierarchy` VALUES ('hierarchy800', 'FMC', 'Kilwani', 'hierarchyLevelId5', 'hierarchy187');
INSERT INTO `locationhierarchy` VALUES ('hierarchy801', 'MCN', 'Mchinga', 'hierarchyLevelId5', 'hierarchy187');
INSERT INTO `locationhierarchy` VALUES ('hierarchy802', 'ITZ', 'Salale', 'hierarchyLevelId5', 'hierarchy187');
INSERT INTO `locationhierarchy` VALUES ('hierarchy803', 'SAI', 'Saninga', 'hierarchyLevelId5', 'hierarchy187');
INSERT INTO `locationhierarchy` VALUES ('hierarchy804', 'SIN', 'Simba Ulanga', 'hierarchyLevelId5', 'hierarchy187');
INSERT INTO `locationhierarchy` VALUES ('hierarchy805', 'MFM', 'Mfisini A', 'hierarchyLevelId5', 'hierarchy188');
INSERT INTO `locationhierarchy` VALUES ('hierarchy806', 'MFS', 'Mfisini B', 'hierarchyLevelId5', 'hierarchy188');
INSERT INTO `locationhierarchy` VALUES ('hierarchy807', 'MF ', 'Mfisini kati', 'hierarchyLevelId5', 'hierarchy188');
INSERT INTO `locationhierarchy` VALUES ('hierarchy808', 'SFK', 'Kihingi Shule', 'hierarchyLevelId5', 'hierarchy189');
INSERT INTO `locationhierarchy` VALUES ('hierarchy809', 'KGP', 'Kihingipwani', 'hierarchyLevelId5', 'hierarchy189');
INSERT INTO `locationhierarchy` VALUES ('hierarchy810', 'MJE', 'Mjengea', 'hierarchyLevelId5', 'hierarchy189');
INSERT INTO `locationhierarchy` VALUES ('hierarchy811', 'ZPT', 'Kilwa', 'hierarchyLevelId5', 'hierarchy190');
INSERT INTO `locationhierarchy` VALUES ('hierarchy812', 'MCK', 'Mchikichini', 'hierarchyLevelId5', 'hierarchy190');
INSERT INTO `locationhierarchy` VALUES ('hierarchy813', 'MJW', 'Mjimwema', 'hierarchyLevelId5', 'hierarchy190');
INSERT INTO `locationhierarchy` VALUES ('hierarchy814', 'MPG', 'Mparange', 'hierarchyLevelId5', 'hierarchy190');
INSERT INTO `locationhierarchy` VALUES ('hierarchy815', 'ZIG', 'Msikitini', 'hierarchyLevelId5', 'hierarchy190');
INSERT INTO `locationhierarchy` VALUES ('hierarchy816', 'VIW', 'Viwandani', 'hierarchyLevelId5', 'hierarchy190');
INSERT INTO `locationhierarchy` VALUES ('hierarchy817', 'AMA', 'Amani', 'hierarchyLevelId5', 'hierarchy191');
INSERT INTO `locationhierarchy` VALUES ('hierarchy818', 'AZZ', 'Azimio', 'hierarchyLevelId5', 'hierarchy191');
INSERT INTO `locationhierarchy` VALUES ('hierarchy819', 'OTG', 'Msikitini', 'hierarchyLevelId5', 'hierarchy191');
INSERT INTO `locationhierarchy` VALUES ('hierarchy820', 'SII', 'Siasa', 'hierarchyLevelId5', 'hierarchy191');
INSERT INTO `locationhierarchy` VALUES ('hierarchy821', 'HKC', 'Sokoni', 'hierarchyLevelId5', 'hierarchy191');
INSERT INTO `locationhierarchy` VALUES ('hierarchy822', 'SCH', 'Ujamaa', 'hierarchyLevelId5', 'hierarchy191');
INSERT INTO `locationhierarchy` VALUES ('hierarchy823', 'UMJ', 'Umoja', 'hierarchyLevelId5', 'hierarchy191');
INSERT INTO `locationhierarchy` VALUES ('hierarchy824', 'UME', 'Umwe', 'hierarchyLevelId5', 'hierarchy191');
INSERT INTO `locationhierarchy` VALUES ('hierarchy825', 'MAF', 'Makarafati', 'hierarchyLevelId5', 'hierarchy192');
INSERT INTO `locationhierarchy` VALUES ('hierarchy826', 'LKG', 'Makonge', 'hierarchyLevelId5', 'hierarchy192');
INSERT INTO `locationhierarchy` VALUES ('hierarchy827', 'JKA', 'Makumbusho', 'hierarchyLevelId5', 'hierarchy192');
INSERT INTO `locationhierarchy` VALUES ('hierarchy828', 'GBF', 'Mbuyuni', 'hierarchyLevelId5', 'hierarchy192');
INSERT INTO `locationhierarchy` VALUES ('hierarchy829', 'ULA', 'Msikitini', 'hierarchyLevelId5', 'hierarchy192');
INSERT INTO `locationhierarchy` VALUES ('hierarchy830', 'MWB', 'Mwembe Muhoro', 'hierarchyLevelId5', 'hierarchy192');
INSERT INTO `locationhierarchy` VALUES ('hierarchy831', 'NGS', 'Ngasinda', 'hierarchyLevelId5', 'hierarchy192');
INSERT INTO `locationhierarchy` VALUES ('hierarchy832', 'NJO', 'Njogoro', 'hierarchyLevelId5', 'hierarchy192');
INSERT INTO `locationhierarchy` VALUES ('hierarchy833', 'KTA', 'Kitundu', 'hierarchyLevelId5', 'hierarchy193');
INSERT INTO `locationhierarchy` VALUES ('hierarchy834', 'HJQ', 'Kiwili', 'hierarchyLevelId5', 'hierarchy194');
INSERT INTO `locationhierarchy` VALUES ('hierarchy835', 'YRS', 'Siasa', 'hierarchyLevelId5', 'hierarchy195');
